Only look at kubeclientset pods if needed
argoproj/argo-workflows pull request #10418
Opened 2023-01-28 08:27 UTC by tooptoop4

2023-01-29 06:02 UTC, LinuxSuRen approved these changes
LGTM

2023-01-29 06:03 UTC, LinuxSuRen commented
hi @tooptoop4 I guess you might need to keep the PR template instead of deleting it.

2023-02-12 16:53 UTC, alexec requested changes
Looks good, but can you:

* Sign-off your commits to the DCO check passes.
* Add comments saying why this is a good idea.

2023-04-25 10:23 UTC, tooptoop4 commented
crunchety

2023-04-25 13:59 UTC, terrytangyuan commented on workflow/controller/controller.go
> -		pods := wfc.kubeclientset.CoreV1().Pods(namespace)
This doesn't actually look up pods, it only invokes the API. The patch/delete calls are the actual calls to K8s. I don't see any benefits this brings.

2023-06-18 02:05 UTC, closed without merging