docs: Clarify retry strategies, closes #9337
argoproj/argo-workflows pull request #10450
Opened 2023-02-02 11:54 UTC by caelan-io

Signed-off-by: Caelan U 

Fixes #9337

Please do not open a pull request until you have checked ALL of these:

* [x] Create the PR as draft .
* [x] Run `make pre-commit -B` to fix codegen and lint problems.
* [x] Sign-off your commits (otherwise the DCO check will fail).
* [x] Use [a conventional commit message](https://www.conventionalcommits.org/en/v1.0.0/) (otherwise the commit message check will fail).
* [x] "Fixes #" is in both the PR title (for release notes) and this description (to automatically link and close the issue).
* [ ] Add unit or e2e tests. Say how you tested your changes. If you changed the UI, attach screenshots.
* [ ] Github checks are green.
* [ ] Once required tests have passed, mark your PR "Ready for review".

If changes were requested, and you've made them, dismiss the review to get it reviewed again.

2023-02-02 11:56 UTC, tico24 approved these changes

2023-02-03 15:21 UTC, tico24 approved these changes

2023-02-06 03:16 UTC, terrytangyuan approved these changes

2023-02-06 05:17 UTC, sarabala1979 approved these changes

2023-02-12 16:54 UTC, alexec requested changes
Build failing. Run `make docs` and commit the result.

2023-05-01 08:51 UTC, rohankmr414 requested changes

2023-05-01 08:51 UTC, rohankmr414 commented on docs/retries.md
> +Using `retryPolicy = Always` is the simplest approach to ensure your step is automatically retried for any error or failure, whether in the main, init, or wait containers.
The extra space at the end of this line is the reason behind the failing check.

```suggestion
Using `retryPolicy = Always` is the simplest approach to ensure your step is automatically retried for any error or failure, whether in the main, init, or wait containers.
```

2023-06-18 02:05 UTC, closed without merging