fix: ensure children containers are killed for container sets. Fixes #10491
argoproj/argo-workflows pull request #10639
Opened 2023-03-04 10:08 UTC by isubasinghe

Fixes #10491

Please do not open a pull request until you have checked ALL of these:

2023-03-05 17:52 UTC, alexec commented on workflow/controller/exec_control.go
> +	children := []wfv1.NodeStatus{}
This looks like a useful utility function,:

- Is there already a similar function?
- If not, extract it, e.g. `woc.wf.Status.Nodes.GetTransientChildren(nodeID)`

Extracting it to a function will:

- Allow reuse.
- Write test.

2023-03-05 17:53 UTC, alexec requested changes
Please dismis this review to request re-review.

2023-03-10 16:40 UTC, alexec commented on pkg/apis/workflow/v1alpha1/workflow_types.go
> +func (s Nodes) NestedChildrenStatus(parentNodeId string) ([]NodeStatus, error) {
now, please add tests!

2023-03-10 16:41 UTC, alexec commented on pkg/apis/workflow/v1alpha1/workflow_types.go
> +			q = append(q, s[nodeID])
do we need to go down the tree?

2023-03-17 14:16 UTC, alexec approved these changes

2023-03-21 15:31 UTC, sarabala1979 approved these changes

2023-03-21 15:31 UTC, merged