Update memoization.md
argoproj/argo-workflows pull request #10992
Opened 2023-04-27 10:14 UTC by eriadam

TODO: Say why you made your changes.

The first question I had was about the validity of the cached items. Turns out is is possible to set.

TODO: Say what changes you made.

Added the information about the maxAge parameter of the memoise step feature and a link to its example on Github.

TODO: Say how you tested your changes.

Preview.

2023-04-27 12:21 UTC, terrytangyuan approved these changes

2023-04-27 14:57 UTC, tico24 requested changes

2023-04-28 10:17 UTC, eriadam commented on docs/memoization.md
> +[Find a simple memoise example here](https://github.com/argoproj/argo-workflows/blob/master/examples/memoize-simple.yaml).
Thanks for checking. I've run `make docs` and updated the spelling.

2023-04-28 11:14 UTC, maxsxu approved these changes
LGTM

2023-04-28 11:15 UTC, tico24 approved these changes

2023-05-07 14:56 UTC, maxsxu reviewed
@eriadam It seems your latest commit didn't signed-off, which causes the CI/DCO failed.

2023-05-10 00:20 UTC, merged