feat: allow crossnamespace locking via sempahores
argoproj/argo-workflows pull request #11096
Opened 2023-05-17 12:38 UTC by woehrl01

- feat: allow crossnamespace locking via sempahores

Fixes #TODO

### Motivation

### Modifications

### Verification

2023-05-25 15:41 UTC, woehrl01 commented
@terrytangyuan @jessesuen @alexec highly appreciate your feedback on this. Is there anything missing, to have this merged? Thanks!

2023-05-25 18:20 UTC, terrytangyuan commented
cc @sarabala1979 @isubasinghe

2023-05-28 07:08 UTC, isubasinghe reviewed
Looks good to me. I think this PR should also implement this support for mutexes though. 
It would be somewhat odd if semaphores supported this while mutexes didn't.

2023-05-28 07:09 UTC, isubasinghe commented
The tests pass for me locally, might just be flaky tests, give it a re-run

2023-05-28 09:06 UTC, woehrl01 commented
Thanks for your feedback @isubasinghe I just added the namespace for mutex, too.

2023-05-30 07:28 UTC, isubasinghe commented on api/jsonschema/schema.json
> +          "type": "string"
Namespace is the namespace of the mutex if not the same as the workflow.

2023-05-30 07:28 UTC, isubasinghe commented on api/openapi-spec/swagger.json
> +          "description": "Namespace is the namespace of the configmap if not the same as the workflow",
.

2023-05-30 07:28 UTC, isubasinghe commented on docs/executor_swagger.md
> +| namespace | string| `string` |  | | Namespace is the namespace of the configmap if not the same as the workflow |  |
.

2023-05-30 07:28 UTC, isubasinghe commented on docs/fields.md
> +|`namespace`|`string`|Namespace is the namespace of the configmap if not the same as the workflow|
.

2023-05-30 07:29 UTC, isubasinghe commented on pkg/plugins/executor/swagger.yml
> +        description: Namespace is the namespace of the configmap if not the same as
.

2023-05-30 07:57 UTC, woehrl01 commented
Yes, you're right, I rephrase the comment. Thank you!

2023-05-30 08:11 UTC, isubasinghe commented on docs/executor_swagger.md
> +| namespace | string| `string` |  | `"namespace of workflow)"`|  |  |
fix default here

2023-05-30 08:12 UTC, isubasinghe commented on docs/executor_swagger.md
> +| namespace | string| `string` |  | `"namespace of workflow)"`|  |  |
also here, there is a right paren and its inside `` and "".

2023-05-30 08:12 UTC, isubasinghe reviewed
typo in docs, I made two comments

2023-05-30 08:13 UTC, isubasinghe requested changes
Apoligies: meant to request changes not comment, see previous comment.

2023-05-30 09:55 UTC, woehrl01 commented
Just renamed the default again and put it in brackets to be more visible of a "variable" argument. Unfortunately, I can't remove the quotes, they are added automatically. Alternative would be to put the default into the description, but I'm not a fan of that either.

2023-05-30 10:02 UTC, isubasinghe commented
Thanks for the changes @woehrl01

2023-05-30 10:02 UTC, isubasinghe approved these changes
LGTM

2023-05-31 20:58 UTC, merged