Improved Core Components documentation
argoproj/argo-workflows pull request #11342
Opened 2023-07-12 10:57 UTC by RafaelClovr

### Motivation
The documentation does not talk about Workflows Server and Workflow controller

### Modifications
I added few basic descriptions about that components.

### Verification

2023-07-12 13:40 UTC, terrytangyuan reviewed
@agilgur5 Would you like to help review this?

2023-07-13 01:32 UTC, agilgur5 requested changes
So documentation on the internals is typically placed in an "Architecture" page in most k8s projects. Argo has an ["Architecture" page](https://argoproj.github.io/argo-workflows/architecture/) in the Developer Guide.

We could link to the Architecture page from here, and that page could certainly use more details, but I don't think the architectural details belong on this page, which is part of the User Guide.
A user does not need to know the underlying architecture to get started with Argo, but they certainly may want to. I think a link to the Architecture page would serve better for that purpose

2023-07-13 07:32 UTC, RafaelClovr commented
@agilgur5 I agree, could be interesting to just add the link.

2023-07-13 15:33 UTC, agilgur5 reviewed
@RafaelClovr would you like to update your PR to add a link instead?

I provided a suggestion below as to what that may look like. The Architecture page itself could use a bit more details if you would like to improve that.

Will have to update the title of your PR to be more specific as well, for instance, `docs: link Core Components to Architecture`. CI is also currently failing `markdownlint`

2023-07-13 15:33 UTC, agilgur5 commented on docs/workflow-concepts.md
> +It allows to handle where could we run the Workflow, and let the user restricts which namespace is able to run any Workflow.
```suggestion
## Architecture

If you are interested in Argo's underlying architecture, see [Architecture](architecture.md)
```

2023-07-13 20:35 UTC, agilgur5 commented on docs/workflow-concepts.md
> +
```suggestion
This page serves as an introduction to the core concepts of Argo.
```

We should revert this section addition now that the link at the bottom of the page exists. 
Reverting this should also fix the remaining `markdownlint` CI issues

2023-07-14 13:55 UTC, terrytangyuan approved these changes

2023-07-14 14:18 UTC, merged

2023-07-14 15:43 UTC, agilgur5 commented
Thanks for your contribution @RafaelClovr !
If you'd like to contribute more details to the Architecture page or any other docs, feel free to make additional PRs 🙂