fix: base href does not work #11401 #10194 #2134
argoproj/argo-workflows pull request #11644
Opened 2023-08-21 13:21 UTC by sonbui00

Fix #11401 
Fix #10194 
Related #2134

### Motivation

Support BASE_HREF on the document https://argoproj.github.io/argo-workflows/argo-server/

### Modifications

Add handle base href for static file and test

### Verification
make test

2023-08-21 17:45 UTC, agilgur5 reviewed
Hmm I need to take a look at this more closely, but this looks more like partial rootpath support rather than base href from a glance. 

With just base href, the proxy in front should be rewriting these subpaths. The Argo Server still sees requests from `/`. Or, effectively, base href primarily impacts links, such as those on [the front-end](https://github.com/argoproj/argo-workflows/blob/cbf0ae9171cf3cb33e815ffc252d0e8f14ae22bd/ui/src/app/shared/base.ts#L1)

2023-08-22 00:30 UTC, sonbui00 commented
@agilgur5 what "partial rootpath support" mean? 

> With just base href, the proxy in front should be rewriting these subpaths
=> Can you give me an example?

> The Argo Server still sees all requests from /
=> I tried to keep this compatible with other functions, ex: readiness check

2023-08-22 00:40 UTC, agilgur5 commented
> @agilgur5 what "partial rootpath support" mean?

As in a partial implementation of #7767.

> => Can you give me an example?

#3080 has many examples of ingress config with rewrites. [This one](https://github.com/argoproj/argo-workflows/issues/3080#issuecomment-657956161) from the top is pretty concise and uses the common NGINX IGC

2023-08-22 00:50 UTC, sonbui00 commented
@agilgur5 I'm sorry, but I do not understand. Let's me know if you want any info here

2023-08-23 01:17 UTC, agilgur5 commented
> @agilgur5 I'm sorry, but I do not understand.

Let me try two other explanations:
1. [`<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) is an HTML element. Per the MDN docs, the `href` attribute only affects HTML links. It does _not_ change anything on the back-end.
    - With a Single Page App (SPA) on the UI, JS links also need to be changed. Hence [the JS](https://github.com/argoproj/argo-workflows/blob/cbf0ae9171cf3cb33e815ffc252d0e8f14ae22bd/ui/src/app/shared/base.ts#L1) I linked before.
  
2. `/argotest/main.js` should never occur. The proxy in front of the server is supposed to rewrite that to `/main.js`. The server only sees `/main.js` and never sees `/argotest/main.js` because there is a proxy in front.
    - Without rootpath support (i.e. #3080), the back-end basically has no knowledge of the rewrite. Rootpath support is similar to implementing the rewrite within Argo.

2023-08-23 01:23 UTC, agilgur5 requested changes
I don't think this is actionable as a "fix" to base href. base href is working correctly.

This could be used as part of a feature to implement rootpath (#7767), but that should probably be done as one larger PR

2023-08-23 01:50 UTC, sonbui00 commented
> I don't think this is actionable as a "fix" to base href. base href is working correctly.

Can you make a test? I don't think it work like the document and I also made some test before. That's why many people report this in some issues. Also you can read the fix code to know the reason

2023-08-23 01:56 UTC, sonbui00 commented
@agilgur5 with ingress rewrite, I think this is not a issue. I tried without ingress rewrite for this

2023-08-23 01:57 UTC, agilgur5 commented
> Can you make a test?

The back-end is working correctly. Per https://github.com/argoproj/argo-workflows/issues/11401#issuecomment-1685877020, the Server logs are correct, correctly detecting the environment variable. Per https://github.com/argoproj/argo-workflows/issues/11643#issuecomment-1685871836, the Server correctly sets `<base href="/argo/">`.

That is the only impact to the back-end that base href has. All other impacts are front-end facing.

> That's why many people report this in some issues

Per above, both users' own issues show that it is working correctly.
Per https://github.com/argoproj/argo-workflows/issues/10194#issuecomment-1685866941, I think many users are _misinterpreting_ the base href feature for rootpath, but those are two _separate_ features.
Base href is for the front-end, rootpath is for the back-end.

2023-08-23 01:58 UTC, agilgur5 commented
> @agilgur5 with ingress rewrite, I think this is not a issue. I tried without ingress rewrite for this

Yes exactly! Base href is intended to be used _in conjunction to_ an ingress rewrite

2023-08-23 02:06 UTC, sonbui00 commented
> Yes exactly! Base href is intended to be used in conjunction to an ingress rewrite

@agilgur5 Maybe ingress rewrite added to the document after have this issue. This fix can run without ingress rewrite. The document updated after this issue https://github.com/argoproj/argo-workflows/issues/3080

2023-08-23 02:14 UTC, agilgur5 commented
> This fix can run without ingress rewrite.

That's just a separate feature entirely. That is part of rootpath support #7767. And totally feel free to work on #7767!

Base href and rootpath are just two separate (but related) features. Note that the opening comment of #7767 uses _both_ `--basehref` _and_ `--rootpath` together.

"Base href" _specifically_ is a front-end only feature designed to be used with ingress rewrites. It is making the front-end _aware_ of a back-end configuration. The back-end configuration can be done either with an ingress rewrite _or_ with `--rootpath`.

2023-08-23 02:22 UTC, sonbui00 commented
@agilgur5 
I think it this project basehref and rootpath is the same. You will see that they are set to same value. 
Also please note on https://github.com/argoproj/argo-workflows/issues/7767, purpose of the the issue is to fix `running argo-workflows on a subpath requires rewrites on the reverse proxy `. The suggest about `rootpath` is a way to archive the purpose. I think this PR also fix #7767

2023-08-23 03:36 UTC, agilgur5 commented
> I think in this project basehref and rootpath is the same.

No they are separate, it's just that rootpath was never implemented.
I also think it is good for Argo projects to be consistent where possible (and where it makes sense), so if Argo CD has those as two separate flags, Argo Workflows can implement that consistently.

Moreover, "base href" refers to a Web standard, literally the HTML `base` element and its `href` attribute. I don't think we should redefine a Web standard. Things like that tend to cause more confusion rather than less. We should try to teach users about the existing standards and how they work -- which is why those were good docs changes. We might be able to further improve those docs.

`--rootpath` also would require more changes. Ingress rewrites change the external API route as well (e.g. `my-domain.com/api` -> `my-domain.com/argo/api`). So we'd need to do the same thing for `--rootpath`. https://github.com/argoproj/argo-workflows/issues/7767#issuecomment-1031207499 shows several of the changes in CD required (like the GRPC gateway).

2023-08-23 04:35 UTC, sonbui00 commented
@agilgur5 Could you give me a real life example for rootpath and basehref with different values for running Argo Workflow?

2023-08-23 04:49 UTC, sonbui00 commented
> `my-domain.com/argo/api`with prefix /argo/ -> should work without rewrite on additional controller for #7767

I think my PR do not handle this

2023-08-24 05:56 UTC, sonbui00 commented
@agilgur5 Maybe we also need rootpath to handle all cases. let me try to figure it out

2023-08-26 10:08 UTC, closed without merging

2023-08-27 18:02 UTC, agilgur5 commented
> @agilgur5 Could you give me a real life example for rootpath and basehref with different values for running Argo Workflow?

The main one is an ingress rewrite. For instance, if I have `my-cluster.com` as my main cluster domain and all services as subpaths, then I could have `my-cluster.com/argo-cd/`, `my-cluster.com/argo-workflows/`, `my-cluster.com/argo-events/`, `my-cluster.com/prometheus/`, etc.

If all those services did not support rootpath, it would be easier to configure ingress rewrites for all of them in the same way -- only the subpath would be different between them. If they did all support rootpath, they may all also require different configuration (e.g. a configmap vs a flag vs an env var, etc), so rewrites may be easier/more consistent as well.

I can think of some other wacky use-cases, but that's the only one I can think of off the top of my head that is a "real life example" that I and others have definitely used before.

2023-08-27 18:03 UTC, agilgur5 commented
> I think my PR do not handle this

> @agilgur5 Maybe we also need rootpath to handle all cases. let me try to figure it out

Yea that's what I meant when I said that full rootpath support to handle all cases would require a larger PR.
Feel free to take that on if you want!