fix: controller watches global configMap in the namespace where it is running and not in managedNamespace - fixes #11463
argoproj/argo-workflows pull request #11799
Opened 2023-09-11 19:49 UTC by toblich

Fixes #11463 

### Motivation

There was a bug by which the workflow controller did not pick up changes made to its configMap until its pod was deleted. This only manifestated when the controller is running in a particular namespace (`--namespaced`) but is managing workflows in a different namespace (`--managed-namespace=<some_other_ns>`)

### Modifications

Fixed the namespace that the controller watches for changes made to its own configMap, so that it watches the same namespace that it initially reads. See the analysis in #11463 for more details. 

### Verification

I did manual verification by:
1. Deploying into a cluster using both flags (`--namespaced` `--managed-namespace=<other_ns>`) 
2. Making changes to the config map (e.g. to the workflowDefaults)
3. Reading the controller logs
4. Starting a workflow to validate whether the changed made to the configmap had been picked up or not

I also ran all tests, but given that this bug is related to configmaps and namespaces in a k8s cluster, and I don't see a clear way of simulating that in `workflow/controller/controller_test.go`, I haven't added any new tests, but I'm obviously open to do it if there's any example of how to mock the namespaces and configmaps to actually test the watcher (which, as far as I can tell, relies on k8s control plane actually being there and is thus complicated to test without a real k8s cluster).

2023-09-11 22:59 UTC, agilgur5 approved these changes
Thanks for this fix! As stated in the issue, this may also potentially fix some related issues as well, if this was their root cause.

This is a one-line fix, so I'm ok approving as is with manual verification.

I did verify the codepaths myself that this is logically correct:
1. [`config` controller creation](https://github.com/argoproj/argo-workflows/blob/86ee23a9161b9a38f1985392e8536591ccb9231e/workflow/controller/controller.go#L185) uses `namespace` and _not_ `managedNamespace`
1. `UpdateConfig` [calls `Get`](https://github.com/argoproj/argo-workflows/blob/86ee23a9161b9a38f1985392e8536591ccb9231e/workflow/controller/controller.go#L472) on the `config` controller, which [uses `namespace`](https://github.com/argoproj/argo-workflows/blob/f9bb71da8504cbcda8c8f90463975e0b6a9f0302/config/controller.go#L57).
1. Both of those explain why it still works on initialization, but fails to `watch` correctly

So `WatchFunc` here is the odd one out. And ofc, as stated in PR and issue, the `workflow-controller-configmap` _should_ be in the same namespace as the Workflow Controller.

2023-09-11 23:10 UTC, agilgur5 reviewed
Hmm I do see a potential problem that I [suspected](https://github.com/argoproj/argo-workflows/issues/11463#issuecomment-1714074509) in the issue...

On line 422 below in this same function, `wfc.notifySemaphoreConfigUpdate` is called for _every_ ConfigMap in the namespace. Semaphore configs are indeed in the `managedNamespace`.

This may require two separate watchers if there isn't a separate watcher on semaphores already

2023-09-11 23:27 UTC, agilgur5 commented
So there is a separate watcher. The `configMapInformer` is [created on the `managedNamespace`](https://github.com/argoproj/argo-workflows/blob/86ee23a9161b9a38f1985392e8536591ccb9231e/workflow/controller/controller.go#L1056). But that seems to be used almost exclusively [for `parameters` from ConfigMaps](https://github.com/argoproj/argo-workflows/blob/f9bb71da8504cbcda8c8f90463975e0b6a9f0302/workflow/controller/operator.go#L620) (and [GC cache](https://github.com/argoproj/argo-workflows/blob/f9bb71da8504cbcda8c8f90463975e0b6a9f0302/workflow/controller/cache_gc.go#L28)??), if I'm understanding the code correctly.

That informer should probably be extended to semaphores then if I'm understanding correctly.
(Vaguely related, but the `retryWatcher` should probably be converted to an informer too per https://github.com/argoproj/argo-workflows/issues/11657#issuecomment-1705576977).

Would definitely be good to get someone more familiar with the ConfigMap codepaths. @sarabala1979 wrote some of this code originally in #4421, which is why I requested his review.

2023-09-29 22:28 UTC, juliev0 commented
thanks @toblich for the fix! I just reviewed the [PR](https://github.com/argoproj/argo-workflows/pull/11855) referenced above , which looks like it could get merged soon and takes care of the issue you found as well, so in that case this whole method would go away.

2023-09-30 04:48 UTC, agilgur5 commented
@juliev0 not quite, that PR doesn't actually resolve this issue at all. seems like the author there did not interpret the bug here correctly. See my comment there: https://github.com/argoproj/argo-workflows/pull/11855#issuecomment-1741676801

2023-09-30 05:16 UTC, juliev0 commented
> @juliev0 not quite, that PR doesn't actually resolve this issue at all. seems like the author there did not interpret the bug here correctly. See my comment there: [#11855 (comment)](https://github.com/argoproj/argo-workflows/pull/11855#issuecomment-1741676801)

yes, you're totally right. Not sure how I missed that :|

2023-10-02 01:08 UTC, juliev0 approved these changes

2023-10-02 01:10 UTC, juliev0 requested changes
actually, holding off on approval until maybe we can get some feedback on Anton's questions

2023-10-02 01:20 UTC, agilgur5 commented
After reviewing #11855 in-depth, I am pretty sure that `wfc.notifySemaphoreConfigUpdate` is indeed problematic here and needs moving (it also needs moving in #11855's current state due to the `FilterFunc`).

As far as I understand, that function is responsible for requeueing if a semaphore's ConfigMap value increases in size (say you had a limit of 5 and now allow 10, for example). To retain that functionality, that function call must continue to be called on the managed namespace.

2023-10-02 01:36 UTC, juliev0 commented
@agilgur5 

> for `parameters` from ConfigMaps

Yeah, I see what you're saying. `runConfigMapWatcher()` has been handling both the WorkflowControllerConfigmap and [these](https://argoproj.github.io/argo-workflows/synchronization/) ConfigMaps. It would make sense that the latter live on the managed namespace, same as the Workflows that they're used by.

2023-10-02 01:40 UTC, juliev0 commented
> created on the `managedNamespace`

Are you thinking that instead of using a `RetryWatcher` for the managed namespace, we should take advantage of the informer's [UpdateFunc](https://github.com/argoproj/argo-workflows/blob/86ee23a9161b9a38f1985392e8536591ccb9231e/workflow/controller/controller.go#L1090) since otherwise we're creating an unnecessary Watch?

2023-10-02 02:05 UTC, agilgur5 commented
> we should take advantage of the informer's [UpdateFunc](https://github.com/argoproj/argo-workflows/blob/86ee23a9161b9a38f1985392e8536591ccb9231e/workflow/controller/controller.go#L1090) since otherwise we're creating an unnecessary Watch?

ostensibly, it would be a good idea to re-use an existing Informer such as the `configMapInformer`. that specific line/event handler wouldn't fit though, as it's [filtered on executor plugins](https://github.com/argoproj/argo-workflows/blob/26481a2146107ad0937ef7698c27f3686f93c81e/workflow/controller/controller.go#L1069) (and only runs if there are [executor plugins defined](https://github.com/argoproj/argo-workflows/blob/26481a2146107ad0937ef7698c27f3686f93c81e/workflow/controller/controller.go#L1062)). A new event handler outside of that conditional can be added to work around that though.

I was also concerned in https://github.com/argoproj/argo-workflows/pull/11855#discussion_r1341910749 that the `configMapInformer`'s [label selector](https://github.com/argoproj/argo-workflows/blob/26481a2146107ad0937ef7698c27f3686f93c81e/workflow/controller/controller.go#L1059) may not apply for semaphore configmaps. If that is accurate, we would either need a third ConfigMap Informer (the two in #11855 plus another one) or to modify that one to handle both scenarios (e.g. move the label selector into the `FilterFunc` -- but that could change the indices, so that usage would still need to be further checked)

2023-10-02 02:35 UTC, juliev0 commented
> > we should take advantage of the informer's [UpdateFunc](https://github.com/argoproj/argo-workflows/blob/86ee23a9161b9a38f1985392e8536591ccb9231e/workflow/controller/controller.go#L1090) since otherwise we're creating an unnecessary Watch?
> 
> ostensibly, it would be a good idea to re-use an existing Informer such as the `configMapInformer`. that specific line/event handler wouldn't fit though, as it's [filtered on executor plugins](https://github.com/argoproj/argo-workflows/blob/26481a2146107ad0937ef7698c27f3686f93c81e/workflow/controller/controller.go#L1069) (and only runs if there are [executor plugins defined](https://github.com/argoproj/argo-workflows/blob/26481a2146107ad0937ef7698c27f3686f93c81e/workflow/controller/controller.go#L1062)). A new event handler outside of that conditional can be added to work around that though.
> 
> I was also concerned in [#11855 (comment)](https://github.com/argoproj/argo-workflows/pull/11855#discussion_r1341910749) that the `configMapInformer`'s [label selector](https://github.com/argoproj/argo-workflows/blob/26481a2146107ad0937ef7698c27f3686f93c81e/workflow/controller/controller.go#L1059) may not apply for semaphore configmaps. If that is accurate, we would either need a third ConfigMap Informer (the two in #11855 plus another one) or to modify that one to handle both scenarios (e.g. move the label selector into the `FilterFunc` -- but that could change the indices, so that usage would still need to be further checked).
> 
> I can tackle that if our two contributors here aren't able to pick it up.

Nice deep diving into all of this. Yes, you seem to have become an expert on this.

2023-11-13 14:09 UTC, toblich commented
Closing this PR in favor of #11855, which is doing a much more comprehensive fix and also taking care of #11463

2023-11-13 14:09 UTC, closed without merging