docs: Add Distributed Machine Learning Patterns book
argoproj/argo-workflows pull request #12334
Opened 2023-12-08 20:10 UTC by terrytangyuan

2023-12-08 21:28 UTC, juliev0 requested changes
Should we change the heading "Community Blogs and Presentations" now?

2023-12-08 21:36 UTC, terrytangyuan commented
@juliev0 I don't want to change it just for this one addition since this seems to be a common heading across other Argo subprojects and they may be linked by other projects/resources already.

2023-12-08 21:44 UTC, juliev0 commented
> @juliev0 I don't want to change it just for this one addition since this seems to be a common heading across other Argo subprojects and they may be linked by other projects/resources already.

Okay. If there is a link to it, I wouldn't want to mess that up. Well, let's give it a few days in case anyone else objects. After that I'll let it go. :) (the other option would be to have another heading for this)

2023-12-11 17:57 UTC, juliev0 approved these changes

2023-12-11 18:01 UTC, merged