feat: add workflow templates details list
argoproj/argo-workflows pull request #13283
Opened 2024-06-30 08:27 UTC by panicboat

Fixes #13282

### Motivation

As indicated in the Issue, it is inconvenient that the history is not visible in the WorkflowTemplate details.
CronWorkflow can see it, so I would like to see consistency.

### Modifications

<details>
<summary>No history</summary>

![image](https://github.com/argoproj/argo-workflows/assets/4182311/3a792ce4-e29b-4b82-93cb-2e85874ae375)
![image](https://github.com/argoproj/argo-workflows/assets/4182311/375e172b-9932-4f3d-beb1-d9f3979377f8)
![image](https://github.com/argoproj/argo-workflows/assets/4182311/2307d5b6-5a30-4ead-9306-bdd993d48a95)
![image](https://github.com/argoproj/argo-workflows/assets/4182311/6b687076-83f0-4109-9e0a-c17948ef80ff)
</details>

![image](https://github.com/argoproj/argo-workflows/assets/4182311/6a13b580-c98a-4b1e-bf86-217df9218596)
![image](https://github.com/argoproj/argo-workflows/assets/4182311/6ede2f6e-204c-49be-8606-405825ba94d9)
![image](https://github.com/argoproj/argo-workflows/assets/4182311/2361a570-ea84-496a-bcf9-b71f151ea58d)
![image](https://github.com/argoproj/argo-workflows/assets/4182311/aac46c44-d91a-4587-9713-16a4ece3375d)

### Verification

- [x] no data
- [x] Only the relevant Workflow is displayed in the execution history, even if there are multiple WorkflowTemplates.
- [x] Displayed with no problem even with multiple data.

2024-06-30 15:36 UTC, agilgur5 requested changes
This should look similar to #11811, it seems like there's some unnecessary changes here?

Also given how duplicative this is, we should probably move this out into a separate component rather than repeating it in 3 or 4 separate places. I did actually mention this in https://github.com/argoproj/argo-workflows/pull/11790#discussion_r1320704088, which was before it had too many duplications. We should do that now

2024-06-30 15:36 UTC, agilgur5 commented on ui/src/app/cluster-workflow-templates/cluster-workflow-template-details.tsx
> +                    items: getItems()
this doesn't seem necessary?

2024-06-30 15:36 UTC, agilgur5 commented on ui/src/app/cluster-workflow-templates/cluster-workflow-template-details.tsx
> +                <>
I don't think this extra fragment is necessary either, there's already a fragment surrounding it.

2024-08-09 02:16 UTC, closed without merging

2024-08-12 19:21 UTC, agilgur5 commented
Looks like #13452 was opened to supersede this? @panicboat please use the same PR and resolve comments on the PR instead of opening a new one.

Also if you do open a new one, please make sure to reference the old one. Creating a new one with no references is confusing at best, and entirely misses history and comments at worst.

2024-08-12 19:25 UTC, agilgur5 commented
reopened

2024-08-13 00:47 UTC, panicboat commented
@agilgur5 I should have consulted you before creating a new PR.
It seems I am not authorized to ReOpen.
I can continue this PR if you ReOpen it.
![image](https://github.com/user-attachments/assets/0e86668b-2218-47c6-85d4-4c4bde33690a)

2024-08-13 22:37 UTC, agilgur5 commented
> As to the main issue, I do not have the authority to reopen this PR.

Ah, yea in the future a maintainer can definitely reopen.

> Can you please reopen this PR so I can continue to work on it?

Ironically I now can't reopen this PR because the new one uses the same branch 🙃 
![Screenshot 2024-08-13 at 6 06 10 PM](https://github.com/user-attachments/assets/ac2a129a-9174-4fd4-ac05-4115c49ddf7e)


Let's just move to the new one then, it looks like you resolved the comments here in that one

2024-08-13 22:39 UTC, agilgur5 commented on ui/src/app/cluster-workflow-templates/cluster-workflow-template-details.tsx
> +                <>
Resolved in #13452

2024-08-13 22:39 UTC, agilgur5 commented on ui/src/app/cluster-workflow-templates/cluster-workflow-template-details.tsx
> +                    items: getItems()
Resolved in #13452