refactor(ui): reorganize `shared/utils.ts`
argoproj/argo-workflows pull request #13339
Opened 2024-07-12 06:38 UTC by agilgur5

While writing various PRs, I've had some of these changes in a stash for a while. When working on some recent namespace fix PRs, this refactor felt particularly necessary given all the unrelated functions to namespaces in this file

### Motivation

- this file's main purpose is for namespace manipulation, so rename to `shared/namespaces.ts`
  - and rename `Utils` to `nsUtils` for explicitness as well 
  - generally speaking, "dumping grounds" are not good to have and organizing them when they get large is best practice

- these changes also make these functions easier to unit test and give them proper encapsulation
  - private functions are no longer exported

### Modifications

- `shared/utils.ts` -> `shared/namespaces.ts`
  - `Utils` -> `nsUtils`
   
- several util functions were used in exactly one place, so just move them to that place
  - `statusIconClasses` was only used in `phase-icon.tsx`
  - `isWorkflowRunning`, `isWorkflowSuspended` were only used in `workflow-operations-map.tsx`

- some were only used together with exactly one component, so move to that component
  - `getValueFromParameter` was only used with `ParametersInput`

- others were only used for one section of the UI, e.g. Events or Workflows
  - so move them to a `utils.ts` file there; they are not shared between sections
  - similarly `queryParams` was only used in `services/`

- also simplify some of these functions:
  - with optional chaining
  - by inverting unnecessarily nested conditionals
  - by removing unnecessary singleton structures

### Verification

- Purely stylistic changes, no semantic changes
- `yarn lint`, `test` & `build` all pass

### Future Work

The singleton `nsUtils` may not be necessary, but keeping it as-is right now for simpler diff

2024-07-12 06:43 UTC, agilgur5 commented on ui/src/app/sensors/utils.ts
> -            }
I simplified this quite a bit as the two flags, `hasFailed` and `isRunning`, are mutually exclusive (by the logic here but also in general), so can just return as soon as one of them is hit

2024-07-16 02:01 UTC, agilgur5 commented on ui/src/app/shared/namespaces.ts
> +    return fixLocalStorageString(localStorage.getItem(currentNamespaceKey)) ?? (getUserNamespace() || getManagedNamespace());
ack part of this is accidentally taken from #13347 (merge conflict/stash issues); I'm gonna mark this as draft temporarily as a result. Will rebase once that's merged

2024-08-01 04:15 UTC, agilgur5 commented on ui/src/app/shared/namespaces.ts
> +    return fixLocalStorageString(localStorage.getItem(currentNamespaceKey)) ?? (getUserNamespace() || getManagedNamespace());
Rebased

2024-09-09 23:51 UTC, isubasinghe requested changes
Looks okay, can you please make the CI pass?

2024-09-10 00:12 UTC, agilgur5 commented
Yea, looks like I accidentally added an extra new line during conflict resolution

2024-09-10 00:13 UTC, agilgur5 commented
Should pass now

2024-09-16 08:42 UTC, isubasinghe approved these changes
Code looks fine, I am unsure if we should merge this personally though, just due to future potential git conflicts.

2024-09-16 08:42 UTC, merged

2024-09-20 15:13 UTC, agilgur5 commented
> I am unsure if we should merge this personally though, just due to future potential git conflicts.

Same as I wrote in https://github.com/argoproj/argo-workflows/pull/12539#issuecomment-1901012046, this logic applies to any refactor so this is a strawman, as we ofc don't avoid refactors.
Same as there, conflicts are (much) worse for dep upgrades than code changes as well, but we don't avoid those either.