docs: add deprecations to upgrading guide
argoproj/argo-workflows pull request #13757
Opened 2024-10-15 10:12 UTC by Joibel

### Motivation

#13735 and #13719 highlighted and made some deprecations we'd like to remove in a future release.

### Modifications

To aid in ensuring users notice this also add a brief note on them to the upgrading guide.

### Verification

Links work:
![image](https://github.com/user-attachments/assets/fa84fbe1-f8e8-47f2-ae40-112deb917a91)

2024-10-16 08:43 UTC, tico24 requested changes

2024-10-16 08:43 UTC, tico24 commented on docs/upgrading.md
> +The following features are deprecated and will be removed in a future verison of argo-workflows:
nit: isn't it "Argo Workflows"?

2024-10-16 09:06 UTC, Joibel commented on docs/upgrading.md
> +The following features are deprecated and will be removed in a future verison of argo-workflows:
Done

2024-10-16 09:11 UTC, tico24 approved these changes

2024-10-17 02:20 UTC, isubasinghe approved these changes
LGTM

2024-10-17 07:21 UTC, merged

2024-10-18 04:47 UTC, agilgur5 commented on docs/upgrading.md
> +### Deprecations
This should similarly follow order of importance like with https://github.com/argoproj/argo-workflows/pull/13720#discussion_r1790903329 et al. Deprecations would be less important than breakage