fix: mark taskresult complete when failed or error. Fixes ##12993
argoproj/argo-workflows pull request #13798
Opened 2024-10-23 02:43 UTC by isubasinghe

Fixes #12993 and 13533

### Motivation

It is possible for us to obtain a failure response from the pod:
I believe this happens here: https://github.com/argoproj/argo-workflows/blob/bb5130e841ab02cfe5b65f19c214fe309ca88bce/workflow/controller/operator.go#L1418

If we update the node.Message to this message, the PR https://github.com/argoproj/argo-workflows/pull/13537, which relies on the Message field of the pod will never kick in.

An alternative fix to the one provided here would be to mark the task result incomplete in the code for `accessNodeStatus`.
I chose not to go with this, I do not believe there is ever the case where a node has Failed or Errored, yet we still care about its task results.

### Modifications

We now:
1) mark task results complete when we see Failed | Error
2) do not mark task results incomplete if the node is Failed | Error

### Verification

Unable to verify with  certainty due to being a rare edge case.

2024-10-23 02:54 UTC, isubasinghe commented
/retest

2024-10-23 22:30 UTC, isubasinghe commented
/retest

2024-10-23 23:58 UTC, isubasinghe commented
/retest

2024-10-24 02:02 UTC, isubasinghe commented
Seems to be failing to pull argocli:latest since the imagePullPolicy is Never. 
I guess this image doesn't exist on the cluster ass well.

2024-10-25 01:09 UTC, isubasinghe commented
This won't quite work.

2024-10-25 01:23 UTC, isubasinghe commented
Made a change that checks if the pod exists instead of the node Message.

2024-10-25 02:23 UTC, jswxstw approved these changes
LGTM

2024-10-25 06:02 UTC, isubasinghe commented
/retest

2024-10-25 15:01 UTC, agilgur5 submitted a review, later dismissed
I think this makes sense: if the Task Result exists, that means the Pod at some point existed, and if it no longer exists, then that means it was deleted.

The main race I can think of here is if the Task Result was seen in the Informer before the Pod was.  Wasn't this effectively the purpose of the `POD_ABSENT_TIMEOUT` from #13454?

2024-10-25 15:16 UTC, Joibel commented
> The main race I can think of here is if the Task Result was seen in the Informer before the Pod was. Wasn't this effectively the purpose of the `POD_ABSENT_TIMEOUT` from #13454?

I have a worry around this too. I'd like there to be some timeout between when we've noticed that a pod has disappeared so that a delayed but completed `WorkflowTaskResult` can arrive and be actioned.

As this PR is now I don't think we're guaranteed to see the completed task result before the pod removal event, and something like `POD_ABSENT_TIMEOUT` (or similar) would give us that window.

2024-10-25 15:26 UTC, agilgur5 commented
> As this PR is now I don't think we're guaranteed to see the completed task result before the pod removal event

Ah I actually said the inverse, which is less likely, this variant is more likely and possible too.

2024-10-25 15:30 UTC, Joibel requested changes
Blocking on the basis that @agilgur5 and I both think this needs a time window. https://github.com/argoproj/argo-workflows/pull/13798#issuecomment-2438120218

2024-10-25 15:37 UTC, agilgur5 commented
I approved on the basis that this would catch more races than the code before this, but it creates a few too 😅
A more holistic fix would be great either way for sure

2024-10-28 12:19 UTC, jswxstw approved these changes

2024-10-28 12:22 UTC, isubasinghe commented on workflow/controller/taskresult.go
> +	return time.Since(node.StartedAt.Time) <= envutil.LookupEnvDurationOr("RECENTLY_DELETED_POD_DURATION", 2*time.Minute)
Yeah I was hoping to not be reliant on podReconciliation here, but I decided just check for Completed and then check for FinishedAt instead.

2024-10-28 13:24 UTC, Joibel approved these changes

2024-10-28 15:55 UTC, agilgur5 commented on workflow/controller/taskresult.go
> +	return time.Since(node.StartedAt.Time) <= envutil.LookupEnvDurationOr("RECENTLY_DELETED_POD_DURATION", 2*time.Minute)
Related: https://github.com/argoproj/argo-workflows/pull/13537#discussion_r1738728826

2024-10-28 23:19 UTC, merged