feat: mark memoized node as cached
argoproj/argo-workflows pull request #13883
Opened 2024-11-08 16:18 UTC by MenD32

Fixes https://github.com/argoproj/argo-workflows/issues/13848

### Motivation

when using memoization, its much easier to debug workflows when you can see that nodes have been cached. currently in large workflows you'd have to go over all the nodes one by one to understand if they are cached, or you could go to the timeline tab.
both of those options offer a bad user experience, that becomes worse as the workflows get larger.
   

### Modifications

changed the icon of successful cached nodes to a database icon (from font awesome) to mark them as cached.

### Verification

tested in the UI that it works using the examples/memoized-simple.yaml example

#### screenshots:
first workflow (no cache hit)
<img width="1511" alt="Screenshot 2024-11-08 at 14 53 33" src="https://github.com/user-attachments/assets/2942c041-1c12-4de6-9c78-f6f64cfbd34f">

second workflow (cache hit)
<img width="1511" alt="Screenshot 2024-11-08 at 14 53 50" src="https://github.com/user-attachments/assets/931d0282-7b8a-414f-a9e3-a03d69835654">

2024-11-26 14:47 UTC, elliotgunton commented
I like the choice of icon - for the abstract concept of "cached" it seems to align with the rest of the world https://www.google.com/search?q=icon+to+represent+cache

But replacing the check mark within the node itself might be confusing for existing and new users alike - it looks like it's a step related to database access, and two workflows running the same thing will look quite different. I would suggest an additive approach e.g. an overlaid database symbol - quick sketch from a google slide

![image](https://github.com/user-attachments/assets/47723682-1988-4635-9279-6d194a3ca0c6)

2024-12-05 10:56 UTC, Joibel requested changes
I agree with https://github.com/argoproj/argo-workflows/pull/13883#issuecomment-2501010877, that the complete change of icon isn't good UX, and would prefer something similar to @elliotgunton's suggestion.

2024-12-08 08:11 UTC, MenD32 commented
I've added the requested change, I'm not much of a UI UX designer so if you have any changes you'd like to have to the colors and what not, please share

2024-12-08 08:11 UTC, MenD32 commented
<img width="111" alt="Screenshot 2024-11-26 at 18 21 49" src="https://github.com/user-attachments/assets/58bed814-bef5-468d-ae70-ab30906267a0">

this is the new icon

2025-05-22 15:24 UTC, Adrien-D approved these changes
Approving because the phase will still always be `Succeeded`

2025-05-23 07:23 UTC, Joibel approved these changes
Awesome, thanks for iterating on this.

2025-05-23 07:23 UTC, merged