fix: bump deps for k8schain to fix ecr-login
argoproj/argo-workflows pull request #14008
Opened 2024-12-16 14:53 UTC by Joibel

Speculatively fixes #13947

### Motivation

Users of magically logged into ECR appears to have broken in 3.6. It's unclear if this is IRSA that's broken at this stage.

### Modifications

Bump everything used by [container_registry_index.go](https://github.com/argoproj/argo-workflows/blob/main/workflow/controller/entrypoint/container_registry_index.go)

```
go get  github.com/google/go-containerregistry/pkg/authn/k8schain 
go get github.com/awslabs/amazon-ecr-credential-helper/ecr-login
go get  github.com/google/go-containerregistry/pkg/v1/remote
go get  github.com/google/go-containerregistry/pkg/name
go mod tidy
```

### Verification

Untested. This won't be merged unless someone verifies that it helps.

If you are interested in testing this please build your own image using `make workflow-controller-image`. I can build one for you, but you shouldn't take random images from a stranger on the internet really.

2024-12-17 19:59 UTC, tooptoop4 requested changes
need https://github.com/tektoncd/pipeline/pull/7921/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R143

2024-12-23 10:11 UTC, Joibel commented
> need https://github.com/tektoncd/pipeline/pull/7921/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R143

@tooptoop4 Have you verified this? We're not apparently pulling in `github.com/aws/aws-sdk-go-v2` below 1.23.0.

2024-12-23 16:43 UTC, tooptoop4 commented
https://github.com/google/go-containerregistry/blob/main/pkg/authn/k8schain/go.mod#L31

2025-01-10 08:02 UTC, lens0021 commented
> If you are interested in testing this please build your own image using make workflow-controller-image. 

I've tried this, built an image and deployed it. I added the following values as I am using the helm chart.

```
  controller:
    image:
      # https://github.com/argoproj/argo-workflows/issues/13947
      registry: [MY_REGISTIRY]
      repository: [REPOSITORY]
      tag: argo-workflows-3.6.2-gh-14008
```

After doing that, the workflows which has private images served by AWS ECR succeed to run, though on 3.6.2.

@Joibel Is there another thing I can do to help this will be merged?

2025-02-04 21:09 UTC, terrytangyuan approved these changes
Thanks!

2025-02-04 21:09 UTC, merged

2025-02-05 14:54 UTC, Joibel commented
/cherry-pick release-3.6

2025-02-11 08:30 UTC, Joibel commented
I failed to backport this (it fails to automatically backport and I forgot the manual version). It's in progress and will be in the next 3.6 release, which I'll try to do sooner rather than later.

2025-02-14 17:23 UTC, emeier commented
@Joibel thanks for this fix! we're doing some cluster migrations and this is currently blocking us, don't want to go back to 3.5 so eagerly awaiting the release.