refactor:  artifacts table Fixes #8306
argoproj/argo-workflows pull request #14037
Opened 2024-12-29 15:58 UTC by Unperceivable

Fixes #8306

### Motivation

From original [issue]
> It takes time to read and understand artifact info now, especially on first columns whose values that may merge with each other.
(https://github.com/argoproj/argo-workflows/issues/8306)
![previous implementation](https://user-images.githubusercontent.com/48029150/161403294-4db609a5-241e-48a9-875d-3d15ed60d8f6.png)

### Modifications

Refactored workflow-details artifacts white-box to include table columns and expand a cell with text too long for it's cell on hover.
![image](https://github.com/user-attachments/assets/092ec1ad-6d0a-4d58-947e-18c6a203d405)

Added same functionality to workflow-node-info -> inputs/outputs
![image](https://github.com/user-attachments/assets/3279bac0-d68c-4c1f-a5ae-7576320ef1c3)

### Verification

2024-12-30 11:01 UTC, tczhao commented on ui/src/workflows/components/workflow-artifacts.tsx
> +                    <div className='columns download'>Download</div>
The download symbol in each row is self-explanatory enough.
we probably don't need this download column, or download column name, what do you think?

2024-12-30 11:24 UTC, tczhao requested changes
The table seems to resize when hovered at the cell, could you fix that

2024-12-30 12:20 UTC, Unperceivable commented
> The table seems to resize when hovered at the cell, could you fix that  
That was the intended change, from Modifications:  
> expand a cell with text too long for it's cell on hover.  
The alternative suggested in the ticket was a horizontal scroll feature. I figured there would be edge cases where some columns would not appear until you scroll.  
I am fine implementing whatever solution though.

2024-12-30 13:29 UTC, tczhao requested changes
Thank you for the fix, last few things:
1. Could you make sure the table values align with the column name, e.g., left align? People will definitely raise an issue about this later on.
![image](https://github.com/user-attachments/assets/03b88749-e641-4e1f-ab37-0df34030a6b5)
2. we are already on artifact panel, rather than "Artifact Name", using "Name" is probably sufficient enough
![image](https://github.com/user-attachments/assets/24bc90ad-1a55-4d15-a898-0233c40cd0f8)

4. I think we better have the timeformat switch button at the column title instead of individual artifact table value, just like the workflow list page. (we could tackle this in a separate PR, create an issue for this and a separate PR)
![image](https://github.com/user-attachments/assets/fa84d944-d8dd-449b-b62f-05d9892478a2)

2024-12-31 13:23 UTC, Unperceivable commented
> 1. Could you make sure the table values align with the column name, e.g., left align? People will definitely raise an issue  

Fixed padding issue ef7e1a11b  
> 2. we are already on artifact panel, rather than "Artifact Name", using "Name" is probably sufficient enough

Renamed column. but not in the node overview since there is no label to define artifacts in input/output 2f3b9da87   
> 3. I think we better have the timeformat switch button at the column title instead of individual artifact table value, just 
 like the workflow list page. (we could tackle this in a separate PR, create an issue for this and a separate PR)   

Moved timestamp switch to column fe5110658  
![image](https://github.com/user-attachments/assets/e0a684b2-caed-4d94-bd61-01f71118d32a)  
![image](https://github.com/user-attachments/assets/242796a6-9f44-4b6e-87a7-0f11a9a68b37)

2024-12-31 19:31 UTC, tczhao approved these changes
looks great! Thanks for the contribution and happy new year

2024-12-31 19:32 UTC, merged