feat: Fixes #8646 visualize wf before submitting
argoproj/argo-workflows pull request #14034
Opened 2024-12-27 13:18 UTC by Unperceivable

Fixes #8646 

### Motivation

Stumbled across the open [issue](https://github.com/argoproj/argo-workflows/issues/8646) while developing a complex workflow, thought I might as well give it a go myself.

#### Disclaimer
First time doing any front-end development.

### Modifications

Added a "graph view" tab to all workflow/template creation/submission pages to visualize the workflow as a graph before submission.

- Preview graph from submit-new-workflow
![Workflow](https://i.imgur.com/LBEtUKd.png)
- Preview graph from submit-new-workflow using workflowTemplateRef
![Workflow Ref](https://i.imgur.com/HixVA27.png)
- Preview graph from workflow-templates:
![Workflow Template](https://i.imgur.com/yODlzK8.png)
- Preview graph from cluster-workflow-templates:
![Cluster Workflow](https://i.imgur.com/dy6hBoI.png)
- Preview graph from cron-workflow:
![Cron Workflow](https://i.imgur.com/09wTPok.png)

### Verification

Ran all workflows/workflow-templates under ui/test/ui/ and visually compared the predicted graph view to the resultant output.
- Preview vs Run, Steps example:
![Preview vs Run Steps example](https://i.imgur.com/9tb107W.png)
- Preview vs Run, Dag example:
![Preview vs Run Dag example ](https://i.imgur.com/r5eIRWH.png)
- Preview vs Run, Dag+Steps example:
![Preview vs Dag+Steps](https://i.imgur.com/MiE1PVd.png)

### Possible Improvements
- Add node detail view/panel
- Make it a Graph Editor/Allow workflow modifications through graph view
- Improve general UX
  - Ability to hide node type and/or edge labels
  - Dedicated Color/Icon? Currently using Skipped + Clock becuase Pending(Yellow) was harder to read due to low contrast.
  - Node names/labels are truncated, this may no longer be best option since "executionStrategy" is included in the label.
  - Edge labels are small and hard to read, sometimes overlapping with node names
  - Long node types such as StepGroup do not fit to the node.

2024-12-31 20:19 UTC, tczhao requested changes
Looks incredible!

2024-12-31 20:19 UTC, tczhao commented on ui/src/shared/components/editors/graph-viewer.tsx
> +            });
cluster workflow template use case is missing
https://github.com/argoproj/argo-workflows/tree/main/examples/cluster-workflow-template

2024-12-31 20:19 UTC, tczhao commented on ui/src/shared/components/editors/graph-viewer.tsx
> +        });
need to handle error if template is not found

2025-01-01 11:43 UTC, Unperceivable commented on ui/src/shared/components/editors/graph-viewer.tsx
> +            });
Just to clarify, the usecase is for when you manually submit a workflow using workflowTemplateRef for a clusterWorkflowTemplate?  Because currently there is no way to select a clusterWorkflowTemplate directly via the UI right?  
![image](https://github.com/user-attachments/assets/8dec1f3c-9718-447d-9e94-d1d94e4d555b)
I assumed clusterWorkflowTemplates could not be submitted via reference for some reason...

2025-01-01 12:17 UTC, Unperceivable commented on ui/src/shared/components/editors/graph-viewer.tsx
> +        });
Added error handling: 180a14222
![image](https://github.com/user-attachments/assets/5eb02db7-1c6f-4357-8764-a396a443b60c)

2025-01-01 12:18 UTC, Unperceivable commented on ui/src/shared/components/editors/graph-viewer.tsx
> +            });
Added clusterWorkflowTemplate reference support: 180a14222
![image](https://github.com/user-attachments/assets/52c8e742-955f-4ae8-8cba-8668de68acd8)

2025-01-01 12:19 UTC, Unperceivable commented on ui/src/shared/components/editors/graph-viewer.tsx
> +            });
kind is optional so I have to cascade the calls either way.

2025-01-01 19:23 UTC, tczhao commented on ui/src/shared/components/editors/graph-viewer.tsx
> +            });
Thanks for all the screenshots and commit ref, they are really helpful

---

For `workflowTemplateRef` to use clusterworkflow template, the `clusterScope: true` needs to be there, perhaps we should use this to determine if we should do a clusterworkflow template lookup instead of the current fallback method

2025-01-02 10:13 UTC, Unperceivable commented on ui/src/shared/components/editors/graph-viewer.tsx
> +            });
ah ok, clusterScope is also optional but has to be available when it's a cluster template. That makes sense, thanks for explaining.   
Updated the logic: 0fdb470c8

2025-01-08 06:02 UTC, tczhao approved these changes

2025-01-08 06:02 UTC, merged

2025-05-09 07:22 UTC, mohdmsl commented
I see that this feature has been merged but has this been not released?

2025-08-12 15:11 UTC, amit-disc commented
Any Update on this? I also don't see this feature in the UI

2025-08-18 18:23 UTC, tadeboro commented
As far as I can tell, this was released as part of the v3.7 version that was released cca. 1 month ago.