Fix namespace parallelism. Fixes  #10985
argoproj/argo-workflows pull request #14039
Opened 2024-12-30 22:28 UTC by isubasinghe

Fixes #TODO

### Motivation

### Modifications

### Verification

2025-01-02 00:28 UTC, isubasinghe commented
/retest

2025-01-02 01:00 UTC, isubasinghe commented
/retest

2025-01-03 03:05 UTC, isubasinghe commented
/retest

2025-01-03 03:33 UTC, isubasinghe commented
/retest

2025-01-05 23:48 UTC, isubasinghe commented
/retest

2025-01-06 02:05 UTC, MasonM commented
@isubasinghe The E2E tests are broken due to a bug in Kit. I have a fix for it in https://github.com/argoproj/argo-workflows/pull/14048. Could you please review that PR?

2025-01-06 02:26 UTC, isubasinghe commented
/retest

2025-01-06 02:31 UTC, isubasinghe commented
> @isubasinghe The E2E tests are broken due to a bug in Kit. I have a fix for it in #14048. Could you please review that PR?

Thanks, I will do

2025-01-06 04:59 UTC, isubasinghe commented
/retest

2025-01-06 05:09 UTC, isubasinghe commented
/retest

2025-01-06 10:51 UTC, Joibel requested changes
Also needs some documentation in `docs/parallelism.md` to document that when using namespaceParallelism a lower priority workflow in a namespace that has capacity will run before a high priority workflow in a namespace with no capacity.

I assume this is the intentional behaviour - it feels the sane option.

2025-01-06 10:51 UTC, Joibel commented on workflow/sync/multi_throttler_test.go
> +	throttler := NewMultiThrottler(2, make(map[string]int), 2, func(key string) { queuedKey = key })
The original test had no namespace parallelism, so the second 2 here perhaps should be 0 to better mimic that test.

2025-01-06 10:51 UTC, Joibel commented on workflow/sync/multi_throttler.go
> +	cnts := make(map[string]int)
This dubiously named variable appears to be write only, remove?

2025-01-06 10:51 UTC, Joibel commented on workflow/sync/multi_throttler.go
> +		namespaceParallelism:        namespaceParallelism,
I understand why you have this, but as it is unusable by workflow users and I had imagined it might be a callback (to copy the pattern set by `queueFunc`) I wonder if we should keep in in this PR?

I'm OK with leaving it in, it's just a bit odd in this PR.

2025-01-06 10:51 UTC, Joibel commented on workflow/sync/multi_throttler.go
> +	count := 0
Suggest early exit if setLimit==0 to save counting all the semaphores.

2025-01-06 10:51 UTC, Joibel commented on workflow/sync/multi_throttler_test.go
> +}
This test proves the priority between namespaces behaves as I suggest we document it:

```
func TestPriorityAcrossNamespaces(t *testing.T) {
	throttler := NewMultiThrottler(3, make(map[string]int), 1, func(Key) {})
	throttler.Add("a/0", 0, time.Now())
	throttler.Add("a/1", 0, time.Now())
	throttler.Add("a/2", 0, time.Now())
	throttler.Add("b/0", 1, time.Now())
	throttler.Add("b/1", 1, time.Now())
	throttler.Add("b/2", 1, time.Now())

	assert.True(t, throttler.Admit("a/0"))
	assert.True(t, throttler.Admit("b/0"))
	assert.False(t, throttler.Admit("a/1"))
	assert.False(t, throttler.Admit("a/2"))
	assert.True(t, throttler.Admit("b/0"))
	assert.False(t, throttler.Admit("b/1"))
	assert.False(t, throttler.Admit("b/2"))
	throttler.Remove("a/0")
	assert.False(t, throttler.Admit("b/1"))
	assert.True(t, throttler.Admit("a/1"))
	throttler.Remove("b/0")
	assert.True(t, throttler.Admit("b/1"))
	assert.False(t, throttler.Admit("a/2"))
}
```

2025-01-06 14:51 UTC, Joibel commented on workflow/controller/controller_test.go
> +		controller.wfQueue.Forget(key)
Why this change?

2025-01-06 23:01 UTC, isubasinghe commented on workflow/sync/multi_throttler.go
> +		namespaceParallelism:        namespaceParallelism,
I could hide the implementation detail (map as an argument) from this PR in that case. I mean to immediately follow up with a PR that passes in a config containing limits for each namespace.

2025-01-07 00:20 UTC, isubasinghe commented on workflow/sync/multi_throttler.go
> +	cnts := make(map[string]int)
hahahaha, yes I meant to remove this, thanks.

2025-01-07 02:01 UTC, isubasinghe commented on workflow/controller/controller_test.go
> +		controller.wfQueue.Forget(key)
It was a bug in the previous test I believe, if the rate limiter has any entries, it will be added later. This is makes the test flakey as a result because it now relies on timings.

2025-01-07 06:36 UTC, isubasinghe commented
/retest

2025-01-07 06:42 UTC, isubasinghe commented
/retest

2025-01-07 07:29 UTC, isubasinghe commented
/retest

2025-01-07 07:30 UTC, isubasinghe commented
The test have gotten flakier, unsure if this contributed or something else did.

2025-01-07 09:44 UTC, Joibel commented on workflow/controller/controller_test.go
> +		controller.wfQueue.Forget(key)
:+1:

2025-01-07 09:44 UTC, Joibel commented on workflow/sync/multi_throttler.go
> +		namespaceParallelism:        namespaceParallelism,
This will presumably not be a constant map (as in parallelism for a namespace will be modifyable on the fly without restarting the controller). The expectation was an annotation on the namespace or a configmap in the namespace.

2025-01-07 09:44 UTC, Joibel commented on workflow/sync/multi_throttler_test.go
> +}
Did you intend to add this test case - I assume that's what a :+1: might have meant

2025-01-09 02:49 UTC, isubasinghe commented
/retest

2025-01-09 03:47 UTC, isubasinghe commented on workflow/sync/multi_throttler.go
> +		namespaceParallelism:        namespaceParallelism,
No it will not be, I will follow up with a change to make it dynamic.

2025-01-09 03:48 UTC, isubasinghe commented on workflow/sync/multi_throttler_test.go
> +}
Ah I meant to add this, sorry

2025-01-09 23:26 UTC, merged

2025-01-27 17:04 UTC, Joibel commented
This PR seems to be the cause of the SignalsSuite test failures - they almost always fail with this change, and reverting makes them much better.