Corrected the documentation of globalName
argoproj/argo-workflows pull request #4943
Opened 2021-01-25 09:24 UTC by sylock

Previously it was documented that the globalname is stored in workflow.status.outputs.parameters but it is in workflow.outputs.parameters.XXXX

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

2021-01-25 09:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo?pullRequest=4943) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo?pullRequest=4943) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo?pullRequest=4943) it.</sub>

2021-01-25 15:34 UTC, alexec commented
fields.md in auto generated. You’ll need to change the code it is generated from and run ‘make codegen’.

could you please sign off your commits to pass the DCO?

Otherwise looks good!

2021-01-27 02:48 UTC, simster7 commented
FYI: this doc is generated from `workflow_types.go`, you'll need to change that file and run `make codegen` again

2021-02-02 17:01 UTC, simster7 commented
@sylock Bump! Still working on this?

2021-02-02 19:22 UTC, sylock commented
I tried but I'm not a go dev and I get an error when doing a `make codegen`:
```
make: *** No rule to make target '/bin/protoc-gen-gogo', needed by 'pkg/apis/workflow/v1alpha1/generated.proto'
```

2021-02-03 14:53 UTC, simster7 commented
Either

```
go get github.com/gogo/protobuf/protoc-gen-gofast
```

or 

```
go get github.com/gogo/protobuf/protoc-gen-gogo
```

should work

2021-02-03 15:41 UTC, sylock commented
```
sylock@pop-os:~/dev/argo$ go get github.com/gogo/protobuf/protoc-gen-gofast
go: downloading github.com/gogo/protobuf v1.3.2
go: found github.com/gogo/protobuf/protoc-gen-gofast in github.com/gogo/protobuf v1.3.2
go: github.com/gogo/protobuf upgrade => v1.3.2

sylock@pop-os:~/dev/argo$ make codegen
go: downloading golang.org/x/sys v0.0.0-20200930185726-fdedc70b468f
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading golang.org/x/net v0.0.0-20201021035429-f5854403a974
go: downloading golang.org/x/text v0.3.3
make: *** No rule to make target '/bin/protoc-gen-gogo', needed by 'pkg/apis/workflow/v1alpha1/generated.proto'.  Stop.

sylock@pop-os:~/dev/argo$ go get github.com/gogo/protobuf/protoc-gen-gogo
go: found github.com/gogo/protobuf/protoc-gen-gogo in github.com/gogo/protobuf v1.3.2

sylock@pop-os:~/dev/argo$ make codegen
make: *** No rule to make target '/bin/protoc-gen-gogo', needed by 'pkg/apis/workflow/v1alpha1/generated.proto'.  Stop.
```

A few questions:
* If I would miss that library I guess that it would need to be added to the dependency definition of the project?
* It would be nice if there was documentation about how to setup a workfing dev environement for argo (I saw the page on the doc, but it's not detailed enough and is primarily focused about seting up of local kubernetes - in my case I have a kubernetes at my disposal - it is more about the dev environement where because of my lack of knowledge of golang, I'm not really able to debug - I would love to dive into golang but currently I don't have the time for this).

2021-02-19 17:52 UTC, alexec commented
bump! please sync with master and fixed build if you still want this

2021-02-22 19:22 UTC, alexec requested changes
See comments.

2021-03-04 05:25 UTC, closed without merging