feat: Add OnTransientError to support retry only on transient errors
argoproj/argo-workflows pull request #4999
Opened 2021-02-03 02:36 UTC by terrytangyuan

Our use case is to retry only on transient errors but opening this PR to discuss if there's any better approach. 

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

2021-02-09 19:13 UTC, alexec approved these changes

2021-02-10 19:46 UTC, alexec requested changes
Please fix tests.

2021-02-10 21:04 UTC, terrytangyuan commented
> Please fix tests.

Fixed. Please take another look.

2021-02-10 21:07 UTC, alexec approved these changes

2021-02-10 21:53 UTC, merged

2023-03-23 21:58 UTC, tooptoop4 commented
@terrytangyuan how to retry on both OnError or OnTransientError?