fix: Append the error message prior to offloading node status
argoproj/argo-workflows pull request #5043
Opened 2021-02-08 14:39 UTC by terrytangyuan

Currently if offloading is not enabled and if the workflow is too large, we will only see `offload node status is not supported` and the original error message is lost. We'd like to expose that information so users will know their workflow is too large by how much and know what to do next.

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

2021-02-08 16:35 UTC, simster7 submitted a review, later dismissed

2021-02-08 17:43 UTC, alexec commented on workflow/hydrator/hydrator.go
> -		err := waitutil.Backoff(writeRetry, func() (bool, error) {
it is impossible for this to happen AFAIK - alwaysOffloadNodeStatus must always false , so the error must be IsTooLargeError

2021-02-08 18:34 UTC, alexec requested changes
I don't understand this fix. This code branch should only even execute if the error is `workflow is longer than maximum allowed size.`.

2021-02-08 19:17 UTC, terrytangyuan commented
@alexec We are observing error messages like `offload node status is not supported` in our workflows but the original error message is masked. Here's what the new error message looks like (it's the new test case I added in this PR):

`workflow is longer than maximum allowed size. compressed size 317 > maxSize 260.Tried to offload but encountered error: offload node status is not supported`

> I don't understand this fix. This code branch should only even execute if the error is `workflow is longer than maximum allowed size.`.

Perhaps I misunderstood something here but the code would also execute when `alwaysOffloadNodeStatus == true`.

2021-02-19 17:53 UTC, alexec requested changes
Please sync with master.

2021-02-19 19:03 UTC, terrytangyuan commented
@alexec Rebased but outdated again. I thought rebasing is done after approved and before merging?

2021-02-20 20:12 UTC, alexec approved these changes

2021-02-20 20:12 UTC, merged