feat(executor): Allow transient error when saving resource parameters
argoproj/argo-workflows pull request #5180
Opened 2021-02-23 19:47 UTC by terrytangyuan

We usually have long running tasks such as ML model training as resource type jobs (e.g. Kubeflow training CRDs) and we don't want the executor to fail due to transient errors at the very last phase when saving any of the parameters.

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

2021-02-23 20:14 UTC, alexec requested changes
Can you point me to the tests that verify this?

2021-02-24 03:56 UTC, terrytangyuan commented
@alexec Yep, waiting for https://github.com/argoproj/argo-workflows/pull/5166 to merge and I'll probably do something similar to test an example. Although the transient error part may be non-trivial to test. This pattern is commonly seen throughout the codebase but no e2e test exists yet unless I miss anything. Any suggestions would be appreciated.

2021-02-24 15:21 UTC, terrytangyuan commented on hack/test-examples.sh
> +kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=argo:default -n argo
@alexec Is this okay? Or should we keep additional RBAC manifests that's more fine-grained in a separate folder?

2021-02-24 15:21 UTC, terrytangyuan commented on workflow/executor/resource.go
> +		err := waitutil.Backoff(ExecutorRetry, func() (bool, error) {
@alexec This pattern is commonly seen throughout the codebase and `waitutil.Backoff`+`argoerr.IsTransientErr` are covered in unit tests.  However there's no e2e test yet unless I miss anything. ` examples/k8s-jobs.yaml` exercises part of this code path but not the transient error part. Is this sufficient? Any suggestions would be appreciated.

2021-04-14 15:07 UTC, terrytangyuan commented
Low priority as we only had this problem 3 times. Closing for now.

2021-04-14 15:07 UTC, closed without merging