fix: Allow setting workflow input parameters in UI. Fixes #4234
argoproj/argo-workflows pull request #5319
Opened 2021-03-07 04:16 UTC by kennytrytek

Signed-off-by: Kenny Trytek <kenneth.g.trytek@gmail.com>

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).
I am committing on my own time.

2021-03-12 20:14 UTC, alexec reviewed
this seems not quite there yet to me, it should not matter which entrypoint you have, the parameters should always be `spec.arguments.parameters`

2021-03-12 21:07 UTC, kennytrytek commented
> @alexec 
> this seems not quite there yet to me, it should not matter which entrypoint you have, the parameters should always be `spec.arguments.parameters`

Looking at the example template in the PR description:
Workflow input parameter: `message`
whalesay-template parameter: `message-param-1`
whalesay-template-two parameter: `message-two`

The existing UI is unable to submit the workflow at all because the parameters for whalesay-template and whalesay-template-two do not have default values. How would those values get populated in the workflow submission if they cannot be set in the UI?

2021-03-17 15:56 UTC, alexec commented
Can we break this into 2 PRs?

* One to allow you to choose entrypoint.
* Another where we can discus the arguments.

2021-03-17 20:39 UTC, kennytrytek commented
@alexec, the current UI already allows you to choose an entrypoint, so I don't think there's anything to do for your first bullet point suggestion. This PR should fit the bill for the second bullet point though.

2021-03-18 15:59 UTC, alexec requested changes
I still can't get my head around this. Can I please ask you to attach an example of a workflow template that this would impact?

2021-03-18 18:37 UTC, kennytrytek commented
@alexc, please see the pull request description for an example workflow template and a GIF showing the UI behavior. The original issue has a GIF showing the current UI behavior for that template.

2021-03-18 18:38 UTC, kennytrytek commented
@alexc, please see the pull request description for an example workflow template and a GIF showing the new UI behavior. The original issue has a GIF showing the current UI behavior for that template.

2021-04-08 22:18 UTC, alexec commented on ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-details/cluster-workflow-template-details.tsx
> -                        parameters={template.spec.arguments.parameters || []}
I think we still need these - otherwise how do you submit the workflow template specifying the spec arguments?

2021-04-08 22:18 UTC, alexec commented on ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-details/cluster-workflow-template-details.tsx
> -                        parameters={template.spec.arguments.parameters || []}
I think we still need these - otherwise how do you submit the workflow template specifying the spec arguments?

2021-04-28 16:25 UTC, alexec commented
@kennytrytek I think we want this PR, but I don't want to lose the ability to set the `spec.arguments`. Could I please ask you to support both?

2021-04-28 16:59 UTC, kennytrytek commented
Yes, sorry I've been slow on this; I was prioritizing the WorkflowNodeRunning PR ahead of this one. I understand what you're saying; we need to be able to handle the case where there are workflow input parameters, and not just entrypoint parameters.

My current thought is to add an empty option like `<none>` in the entrypoint selector, using the workflow input parameters for that case.

2021-04-28 17:45 UTC, alexec commented
that sounds good to me

2021-04-28 17:46 UTC, alexec commented
in the future -  I'd like to add the ability to resubmit a workflow with different parameters

2021-06-14 03:36 UTC, kennytrytek commented
Sorry for the slow updates on this one. I tested it with some templates from the examples folder, and it appears to do what I would expect; either entrypoint or workflow parameters can be used.

2021-06-14 14:47 UTC, alexec approved these changes

2021-06-14 14:47 UTC, merged