feat(ui): support any yaml reference in link
argoproj/argo-workflows pull request #5667
Opened 2021-04-13 07:54 UTC by tczhao

Resolves #4752

Signed-off-by: Tianchu Zhao <evantczhao@gmail.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

2021-04-13 13:58 UTC, alexec requested changes
looks really good so far - one change suggested - dismiss this review when ready to review again

2021-04-13 13:58 UTC, alexec commented on ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
> +    const object = props.workflow;
I think we should have an object that is like the node status really.

```
{
                            metadata: {
                                namespace: props.workflow.metadata.namespace,
                                name: props.node.id
                            },
                            workflow: workflow,
                            status: {
                                startedAt: props.node.startedAt,
                                finishedAt: props.node.finishedAt
                            }
                        }}
```

That way you can reference the workflow name, and its started and finished at times.

2021-04-13 13:58 UTC, alexec commented on ui/src/app/shared/components/links.tsx
> +    return url.replace(/\${[^}]*}/g, x => {
this is very smart!

2021-04-13 13:58 UTC, alexec commented on pkg/apis/workflow/v1alpha1/info.go
>  	// Either "workflow" or "pod"
minor - but scope can also be some other things

2021-04-14 15:26 UTC, alexec approved these changes

2021-04-14 15:27 UTC, merged

2021-05-25 09:22 UTC, zewelor commented
Is there any example how to use this ?

2021-05-25 10:00 UTC, tczhao commented
@zewelor 
Hi, you can modify the [links in configmap](https://github.com/argoproj/argo-workflows/blob/master/docs/workflow-controller-configmap.yaml#L41)
using something like _workflow.metadata.annotations.userDefinedKey_ 
the userDefinedKey is from your workflow

note that this feature is only available from master branch at the moment or future 3.1 release

2021-05-25 10:10 UTC, zewelor commented
Got it thanks for reply !