feat: configurable windows os version
argoproj/argo-workflows pull request #5816
Opened 2021-05-04 19:05 UTC by mweibel

Allows to configure the windows version used for argoexec (see #5376). This allows us to easily build a version of the argoexec docker image without the need to adjust the Dockerfile itself (instead just pass `--build-arg IMAGE_OS_VERSION=1909`). 

Fixes #5546 (rebased PR on current master)

The `IMAGE_OS` and `IMAGE_ARCH` build args were unused and hence I removed them. 

possibly @lippertmarkus to review? :) 

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

2021-05-05 04:54 UTC, lippertmarkus requested changes

2021-05-05 04:54 UTC, lippertmarkus commented on Dockerfile.windows
>  FROM mcr.microsoft.com/windows/servercore:ltsc2019 as builder
@mweibel please also use `IMAGE_OS_VERSION` here (`1809` tag also exists for servercore). If one is using process isolation for building the image, the builder image OS version needs to match the host OS as well.

2021-05-07 06:27 UTC, lippertmarkus approved these changes

2021-05-07 15:12 UTC, alexec approved these changes

2021-05-07 15:12 UTC, merged