docs: link to examples with relative link instead of symlink
argoproj/argo-workflows pull request #5959
Opened 2021-05-20 19:20 UTC by jli

/docs/examples is a symlink to /examples, but links that use the symlink
don't work on Github. For instance, the link to the exit-handlers.yaml
example (first link in the doc) is broken:
https://github.com/argoproj/argo-workflows/blob/67a38e33ed1a4d33085c9f566bf64b8b15c8199e/docs/workflow-notifications.md

Sorry, I don't have a go toolchain set up, so I didn't run the pre-commit locally. But I tested that the new links work on Github in my fork:
https://github.com/jli/argo-workflows/blob/1790a2887074c0b895df8e484c9d51395fa25763/docs/workflow-notifications.md

2021-05-24 19:14 UTC, alexec requested changes
The documentation (https://argoproj.github.io/argo-workflows/) is generated from these files. Your change will break that. Instead, you could replace the relative links with absolute links pointing to the raw.* url.

2021-07-08 16:56 UTC, sarabala1979 commented
@jli Can you address the @alexec comments?

2021-07-08 17:08 UTC, jli commented
I'm not sure I understand the request - should the links be absolute links to the raw files hosted on GitHub?

I'm also not sure where these files/links show up on the published documentation site (I tried searching for some text and failed to find them), so I also don't quite understand the original issue that @alexec raised.

2021-08-28 00:36 UTC, alexec commented
fixed on master

2021-08-28 00:36 UTC, closed without merging