docs(installation): add compatible kubernetes version doc
argoproj/argo-workflows pull request #6095
Opened 2021-06-07 05:56 UTC by tczhao

We had an issue where argo-workflow loops failed to monitor/update workflow yaml status on mismatched argo version and gke cluster

upgrading argo to make sure a matching kubectl and kubernetes helps to resolve the issue.

Adding kubernetes version doc may help other users

---

Signed-off-by: Tianchu Zhao <evantczhao@gmail.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

Tips:

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.

2021-06-07 13:21 UTC, terrytangyuan commented on docs/releases.md
> +|-|-|-|
```suggestion
|-|-|
```

2021-06-07 13:21 UTC, terrytangyuan commented on docs/releases.md
> +|3.1|1.18-1.20|
Is there any specific issue that prevents you from using >1.20?

2021-06-21 18:27 UTC, alexec requested changes
please see @terrytangyuan comment

2021-06-22 02:15 UTC, tczhao commented
Thanks for reminding, not sure why my reply didn't show up

@terrytangyuan 
Sorry about the late reply.

(Is there any specific issue that prevents you from using >1.20?)
I'm not aware of any issue. 

The go k8s dependency should be ok, but argo executor uses kubectl to execute [resourceTemplate](https://argoproj.github.io/argo-workflows/fields/#resourcetemplate).
With the [Kubernete version skew policy](https://kubernetes.io/releases/version-skew-policy/), Using an incompatible kubectl version may cause problems

Maybe we should reword this. Would you have any ideas?

2021-06-22 20:15 UTC, terrytangyuan commented
> I'm not aware of any issue.
> 
> The go k8s dependency should be ok, but argo executor uses kubectl to execute [resourceTemplate](https://argoproj.github.io/argo-workflows/fields/#resourcetemplate).
> With the [Kubernete version skew policy](https://kubernetes.io/releases/version-skew-policy/), Using an incompatible kubectl version may cause problems

I think we should document what's compatible or not based on experience. At least I have not encountered any issues yet since we are only using basic functionalities of kubectl.

2021-06-23 00:30 UTC, tczhao commented
Thanks, this makes sense.
Now think about it, I think the issue is with #5976
Argo 3.0 executor defaults to k8sapi instead of docker thus solve the gke1.19 issue

2021-06-23 00:30 UTC, closed without merging