also copy user labels + workflow-template. fixes #6129
argoproj/argo-workflows pull request #6184
Opened 2021-06-21 13:32 UTC by christopheblin

fix argo-workflows#6129

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

Tips:

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.

2021-06-21 13:46 UTC, christopheblin commented
I do not understand why Semantic PR check is failing (the title do start with "fix ..." which should be enough)

2021-06-21 14:37 UTC, christopheblin commented
now, in addition to the semantic PR check, the CI breaks with:

CI / e2e k8sapi

```
# Wait for workflow controller
until lsof -i :9090 > /dev/null ; do sleep 10s ; done
Error: The action has timed out.
```

CI / UI
```
Run git diff --exit-code
...
Error: Process completed with exit code 1.
```

what should I do for the 3 things ?

2021-06-21 14:52 UTC, alexec commented on ui/src/app/archived-workflows/components/archived-workflow-details/archived-workflow-details.tsx
> +            .filter(e => !e.key.startsWith("workflows.argoproj.io/") || e.key === "workflows.argoproj.io/workflow-template");
I think this is the logic you want:

https://github.com/argoproj/argo-workflows/blob/ab786ecba6eb3e9d3fa7a717ded42727b8b64df8/workflow/util/util.go#L629

2021-06-21 18:26 UTC, alexec requested changes
please update cloneLabelsSafely to match the go code, I expect you need to run `yarn lint` and `yarn build` on the UI too

2021-06-22 11:50 UTC, christopheblin commented
@alexec do you expect the whole logic with memoized ? or "just" the part where we copy relevant labels ?  or also keep annotations and OwnerReference ?

note : I dont understand every bit in the go part, especially I am not sure "memoize" make sense at all in the archive use case...

2021-06-22 13:59 UTC, alexec commented
> @alexec do you expect the whole logic with memoized ? or "just" the part where we copy relevant labels ? or also keep annotations and OwnerReference ?
> 
> note : I dont understand every bit in the go part, especially I am not sure "memoize" make sense at all in the archive use case...

I think just look at the parts about labels.

2021-07-08 16:58 UTC, sarabala1979 commented
@christopheblin When can we expect the PR to be addressed comments and ready for review?

2021-07-09 09:21 UTC, christopheblin commented
Sorry, I switched to another subject and I currently have no time to move forward this PR :(

2021-07-14 18:19 UTC, closed without merging

2024-10-22 20:13 UTC, tooptoop4 commented
where @christopheblin

2024-10-24 22:11 UTC, agilgur5 commented
> where @christopheblin

@tooptoop4 this page no longer exists after #11121 and resubmitting uses the resubmit endpoint these days which handles cloning labels after #3638. See also https://github.com/argoproj/argo-workflows/pull/11083