[WIP] Inject Custom CSS URL
argoproj/argo-workflows pull request #6282
Opened 2021-07-05 10:03 UTC by dtaniwaki

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

Tips:

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Fixes #1451

<img width="682" alt="Screen Shot 2021-07-05 at 12 41 58 PM" src="https://user-images.githubusercontent.com/1162120/124450755-b3cd4b80-ddbf-11eb-9404-7ff76be5f68f.png">

2021-07-05 14:41 UTC, dtaniwaki commented on server/static/static.go
> +	extraPath = "/extra/"
Any good path for extra files?

2021-07-05 15:13 UTC, dtaniwaki commented
I updated the code so the server doesn't return 304 on removed extra files.

2021-07-05 16:15 UTC, alexec commented
I suggest doing this different.

1. Add a new variable to get info called “env”. This can be “dev” , “e2e” or “prod”.
2.  Use this to load a CSS file based on the name. Eg dev.css
3. Bundle CSS using those conventional names.
4. Add a new parameter to Argo server, “—env” or “ARGO_ENV”

2021-07-05 16:30 UTC, dtaniwaki commented
Thank you for your suggestion. I have 2 questions for the env idea. 

What env should we use for a locally running argo server?

We could have 2 argo servers with different instance ID in the production. Should we use different env names like prod_1 and prod_2?

2021-07-06 14:28 UTC, dtaniwaki commented
By the way, as for the env-like name, I injected it by the following CSS.

```
    .nav-bar {
      background-color: #3f51b5;
    }
    .nav-bar__logo::before {
      content: 'stg';
      color: white;
      text-align: center;
      display: block;
    }
```

And got the following result.

<img width="63" alt="Screen Shot 2021-07-06 at 10 55 04 PM" src="https://user-images.githubusercontent.com/1162120/124617364-d770be80-deb1-11eb-82ff-06bd26ad35bd.png">

2021-07-06 14:29 UTC, dtaniwaki commented
However, the env idea is also good. I'd like to hear other people's thoughts.

2021-07-12 17:16 UTC, alexec requested changes
See comments.

2021-08-24 06:07 UTC, dtaniwaki commented
Hmm... No other comments.

@jessesuen Do you have any thought about the compatibility with ArgoCD?

2021-11-07 01:59 UTC, closed without merging

2021-11-17 03:08 UTC, kenchan0130 commented
Is there any progress on this?
I'd like to apply CSS with `values` as well as Argo CD.

2024-10-22 20:07 UTC, tooptoop4 commented
where @dtaniwaki