fix: support archive.none for OSS directory artifacts
argoproj/argo-workflows pull request #6312
Opened 2021-07-08 22:29 UTC by jibuji

to fix problem: #6293 
I have used the following workflow to test, and the result is correct.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-archive-none
spec:
  entrypoint: oss-getter-and-uploader
  templates:
  - name: oss-getter-and-uploader
    inputs:
      artifacts:
      - name: oss-none-empty-dir
        path: "/mnt/input/none-empty"
        oss:
          key: "some/none-empty"
        archive:
          none: {}
      - name: oss-empty-dir
        path: "/mnt/input/empty-dir"
        oss:
          key: "some/emptydir"
        archive:
          none: {}
      - name: oss-file
        path: "/mnt/input/file"
        oss:
          key: "some/file"
        archive:
          none: {}
      - name: oss-3level
        path: "/mnt/input/3level"
        oss:
          key: "some/3level-dir"
        archive:
          none: {}
    container:
      image: 'alpine:latest'
      command: ['/bin/sh', '-c']
      args: ["cp -rf /mnt/input /mnt/output"]
      volumeMounts:
        - name: out
          mountPath: /mnt
    volumes:
      - name: out
        emptyDir: { }
    outputs:
      artifacts:
      - name: oss-none-empty-dir
        path: "/mnt/output/none-empty"
        oss:
          key: "some2/none-empty"
        archive:
          none: {}
      - name: oss-empty-dir
        path: "/mnt/output/empty-dir"
        oss:
          key: "some2/emptydir"
        archive:
          none: {}
      - name: oss-file
        path: "/mnt/output/file"
        oss:
          key: "some2/file"
        archive:
          none: {}
      - name: oss-3level
        path: "/mnt/output/3level"
        oss:
          key: "some2/3level-dir"
        archive:
          none: {}
```

Thanks to @terrytangyuan  a lot.  He helped me to rectify some code, but I failed to commit the PR because my mistake. So, I open this one and commits again.

2021-07-09 00:08 UTC, terrytangyuan commented
Original review feedback is in https://github.com/argoproj/argo-workflows/pull/6296

2021-07-09 00:08 UTC, terrytangyuan approved these changes
LGTM. All feedback in previous review have been addressed.

2021-07-09 02:30 UTC, jibuji commented
Thanks. What should I do next? This is my first time to contribute.

2021-07-09 14:40 UTC, terrytangyuan commented
We'll need to wait for one of the approvers to take another look to see if there are additional feedback before merging.

2021-07-14 14:59 UTC, alexec requested changes

2021-07-14 14:59 UTC, alexec commented on USERS.md
> +1. [Galixir](https://www.galixir.com/)
Should be alphabetical

2021-07-15 20:13 UTC, jibuji commented on USERS.md
> +1. [Galixir](https://www.galixir.com/)
Fixed

2021-07-27 18:15 UTC, sarabala1979 commented
@jibuji PR looks good. can you add a test?

2021-07-27 18:20 UTC, alexec approved these changes

2021-07-27 19:12 UTC, merged