fix(emissary): throw argo error on file not exist
argoproj/argo-workflows pull request #6392
Opened 2021-07-21 10:50 UTC by AntoineDao

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

re #6391 

I took the liberty of not adding tests because it's a 1 line change and there are currently no tests for the emissary executor :stuck_out_tongue:

2021-07-21 16:01 UTC, alexec requested changes
Great stuff!

For testing executors, we write e2e tests. Could you please add one? That way we can be confident the change works, and won't get reverted.

2021-07-26 15:42 UTC, alexec approved these changes

2021-07-26 16:19 UTC, AntoineDao commented
Sorry for not getting around to writing the additional `e2e` tests here. It's been a busy week 😅

2021-07-26 19:21 UTC, alexec requested changes
Please run `make lint`.

2021-07-27 16:51 UTC, sarabala1979 approved these changes

2021-07-27 17:15 UTC, alexec approved these changes

2021-07-27 17:15 UTC, merged