fix(controller): Same workflow nodes are not executing parallel even semaphore locks available
argoproj/argo-workflows pull request #6418
Opened 2021-07-24 17:52 UTC by sarabala1979

closes #6110 

Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

Tips:

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.

2021-07-25 18:53 UTC, sarabala1979 commented on workflow/sync/semaphore.go
> +		if holderKey != nextKey && !isSameWorkflowNodeKeys(holderKey, nextKey) {
We don't want to prioritize/order the same workflow nodes. The executetemplate will make sure the template order.

if the workflow has multiple nodes to wait for lock, the operator node order and semaphore queue order are going out of sync. if it same workflow key

2021-07-26 21:23 UTC, alexec requested changes
please clean-up PR

2021-07-27 01:21 UTC, sarabala1979 commented
> please clean-up PR

done. I missed to cleanup my env

2021-07-27 18:19 UTC, alexec approved these changes

2021-07-27 18:37 UTC, merged