feat(server): support changing MaxGRPCMessageSize using env variable
argoproj/argo-workflows pull request #6420
Opened 2021-07-25 07:55 UTC by dpeer6

…AGE_SIZE to argo-server

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

Tips:

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.

2021-07-25 08:58 UTC, dpeer6 commented
@alexec
This is the updated PR for the MaxGRPCMessageSize override using env varibale to argo-server deployment

2021-07-26 15:39 UTC, alexec approved these changes

2021-07-26 16:02 UTC, alexec requested changes
```
Documented variable GRPC_MESSAGE_SIZE in docs/environment-variables.md is not used anywhere
```

This is a bug in check-env-doc.sh, it does not include `./server`. Should be easy to fix and run.

2021-07-26 16:28 UTC, alexec approved these changes

2021-07-26 16:29 UTC, dpeer6 commented
I updated hack/check-env-doc.sh and now the test passes.. for me at least.

2021-07-27 13:30 UTC, dpeer6 commented
Hi @alexec 
Is there something else I can/should do to get this PR merged?
I see some tests FAILED but not sure it is related to that change

2021-07-27 16:36 UTC, alexec commented
* `E2E Tests (test-cli, emissary, mysql)` this is not failing on `master` so could be a new bug (not sure how mind you!). 
* `Lint` this is failing because ` Error: File is not `goimports`-ed with -local github.com/argoproj/argo-workflows/ (goimports)`. Run `make lint`. Sometimes it is helps to delete any blank lines in your imports and this forces it to sort them.

2021-07-27 17:17 UTC, alexec commented
So the build is failing for a good reason, because the CLI is now printing:

`time="2021-07-27T17:05:31Z" level=info msg="GRPC Server Max Message Size, MaxGRPCMessageSize, is set" `

So I was wrong. Don't print this is `init()`, I think you'll need to revert to your previous solution.

2021-07-28 07:20 UTC, dpeer6 commented
@alexec 
I moved the info logging message to the func that actually starts argo server.
hope that now it pass.
My local tests pass.

2021-07-28 15:23 UTC, merged

2021-07-28 15:24 UTC, alexec commented
Merged at last!

2024-05-04 04:02 UTC, agilgur5 commented on docs/environment-variables.md
> +You can set environment variable for the argo-server deployment, for example:
This is the section for the Controller, not the Server. It seems like a section for the Server did not exist at the time of this PR?

I moved it in #12148