Annotate pod events with workflow name and UID
argoproj/argo-workflows pull request #6455
Opened 2021-07-29 21:43 UTC by josephmcgovern-wf

### Story
With the ability to configure node events to be sent with the involved
object set to the pod, it would be handy if annotations were provided
in the event that would allow the pod/node to understand which workflow
it belongs to.

### Testing

* Run the server locally
* Submit a workflow
* Print out the events and their annotations

### Test results

✅ confirmed that pod events included workflow annotations. Here is an example:

<img width="560" alt="Screen Shot 2021-07-29 at 4 40 00 PM" src="https://user-images.githubusercontent.com/5930159/127569452-4abc8af7-6923-4bbf-8c66-29e528e1cbd6.png">

✅ confirmed that events for the workflow did not contain these annotations (e.g. the `WorkflowRunning` event)
✅ confirmed that non-pod events did not contain these annotations (e.g. `WorkflowNodeRunning` events for a DAG node type):
<img width="433" alt="Screen Shot 2021-07-29 at 4 43 03 PM" src="https://user-images.githubusercontent.com/5930159/127569709-e17b4e69-ccf0-454c-b09c-52ad575d712c.png">

### Notes

I couldn't find a good way to assert that events had certain annotations in the unit tests. I attempted to use If anyone has a good idea on how to do that, I'm open to hearing it. I attempted to do something like:
```golang
controller.kubeclientset.CoreV1().Events(woc.wf.GetNamespace()).List(ctx, metav1.ListOptions{})
```

But that would always return an empty list

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

Tips:

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.

2021-07-29 22:10 UTC, kennytrytek-wf commented on workflow/common/common.go
> +	AnnotationKeyWorkflowName = workflow.WorkflowFullName + "/workflow-name"
All the other entries in this constant have a comment explaining what they are for. It would be good to add comments for these new entries.

2021-07-30 16:18 UTC, alexec requested changes
Looks great. One change:

Can you please make changes to test/e2e/functional_test.go so this is tested?

2021-08-03 20:08 UTC, alexec commented on test/e2e/functional_test.go
> +	configMap.Data["nodeEvents"] = "\n  sendAsPod: true"
where is this change reverted in the test?

2021-08-05 13:54 UTC, josephmcgovern-wf commented
@alexec this should be ready for review

2021-08-06 02:48 UTC, alexec approved these changes

2021-08-06 02:49 UTC, merged