Allow passing in user-defined context to Argo Client Init
argoproj/argo-workflows pull request #6470
Opened 2021-08-02 21:49 UTC by karenin-overseas

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

Hello, this PR adds a `Context` field to the Argo Client opts so a user-defined context can be used in place of `context.Background()`. Basically go programs using the API Client might want the argo client to respect ex. context cancellation on a parent context.

With thanks to the reviewers :)

2021-08-02 22:19 UTC, alexec commented on pkg/apiclient/apiclient.go
> +	Context *context.Context
should not be pointer type

2021-08-02 22:23 UTC, alexec requested changes
Great stuff. Good idea! Some comments...

2021-08-02 22:23 UTC, alexec commented on pkg/apiclient/argo-kube-client.go
> +func newArgoKubeClient(clientConfig clientcmd.ClientConfig, instanceIDService instanceid.Service, baseContext *context.Context) (context.Context, Client, error) {
context should be first arg by convention?

2021-08-02 22:23 UTC, alexec commented on pkg/apiclient/apiclient.go
> +	Context *context.Context
if you add a `GetContext` func, then if `Context` is not set, you could just return `context.Background()`

2021-08-11 16:22 UTC, sarabala1979 commented
@karenin-overseas are you planning to address the review comment and get ready for review?

2021-08-11 17:29 UTC, karenin-overseas commented
> @karenin-overseas are you planning to address the review comment and get ready for review?

Hi @sarabala1979 yes! I'll comment when it's ready for review.

2021-09-10 20:17 UTC, alexec commented
Defunct: #6667

2021-09-10 20:17 UTC, closed without merging