WIP: Allow Users to Specify Kubernetes secret for TLS
argoproj/argo-workflows pull request #6542
Opened 2021-08-13 17:30 UTC by ChaosInTheCRD

Merge After: #6540

This PR allows a user to specify a secret name as a command-line parameter (`--tls-certificate-secret-name`) on the argo-server. Said secret would contain keys `tls.key` and `tls.crt` in order to provide a mechanism by which they can bring their own certificates (e.g. from cert-manager, Bitnami Sealed Secrets, generic Kubernetes secret).

This PR tries to follow a similar implementation to what is seen in Argo CD (https://github.com/argoproj/argo-cd/pull/6071), for maintainability.

Marked as WIP until the following is completed:
- Unit Tests
- Documentation

2021-08-13 20:52 UTC, alexec commented
Change to draft while WIP.

2021-08-20 14:31 UTC, alexec requested changes
Needs sync with master

2021-10-12 11:30 UTC, ChaosInTheCRD commented
@alexec I am looking to take some time, hopefully tomorrow, to get this ready for release. I'll sync it with master, make sure unit tests are written and update documentation.

If there's anything else you need me to do please let me know.

Thanks!

2021-10-31 17:57 UTC, alexec commented on cmd/argo/commands/server.go
> +				if tlsCertificateSecretName != "" {
I think this works well when running locally vs in container.

2021-10-31 17:58 UTC, alexec requested changes
Great stuff. Please:

* [ ] Sync with master.
* [ ] Run `make pre-commit -B` and push changes.
* [ ] Dismiss reviews.

2021-11-30 20:40 UTC, alexec reviewed
is this ready for review again? need any help?

2022-01-19 15:43 UTC, alexec commented on cmd/argo/commands/server.go
> +				tlsMinVersion := env.GetInt("TLS_MIN_VERSION", tls.VersionTLS12)
I'm pretty sure there is existing func for this. Adding a new go.mod dependency increases our vulnerability surface, so please remove this.

2022-01-24 11:09 UTC, ChaosInTheCRD commented
@alexec sorry for not updating this PR in so long. Unfortunately, the state of the commits and the fact that so many of them are signed has held me back. I will fix this now.

2022-01-24 12:47 UTC, ChaosInTheCRD commented
closing this PR in place of https://github.com/argoproj/argo-workflows/pull/7621

2022-01-24 12:47 UTC, closed without merging