docs: adds OpenAPI definitions for artifact routes
argoproj/argo-workflows pull request #6628
Opened 2021-08-31 06:19 UTC by tgallant

Fixes #6606

adds OpenAPI documentation for the following endpoints

/artifacts
/input-artifacts
/artifacts-by-uid
/input-artifacts-by-uid

At first I was considering exposing a grpc service like the other `/api/v1` endpoints. Upon closer inspection that seemed a bit more complicated since you can't just return a `text/plain` response with the logs like the existing artifact service does. With grpc you would need to wrap the data in a message. Instead of trying to rework any of that it seemed much simpler to just add the existing artifiact endpoints to the OpenAPI spec.

2021-08-31 15:25 UTC, alexec commented
I think this is the right way to do this. I think you need to add them to `_.primary.swagger.json` and then run `makeapi/openapi-spec/swagger.json api/jsonschema/schema.json`

2021-09-07 15:25 UTC, alexec requested changes
see comments

2021-09-08 07:21 UTC, tgallant commented
thanks @alexec i moved the path definitions to `_.primary.swagger.json`, ran `make api/openapi-spec/swagger.json api/jsonschema/schema.json`, and committed the changes.

2021-09-08 15:33 UTC, alexec approved these changes

2021-09-08 15:48 UTC, merged