#6396 Add support to continueOn on exit codes
argoproj/argo-workflows pull request #6702
Opened 2021-09-10 19:59 UTC by kriti-sc

2021-09-12 23:05 UTC, sarabala1979 commented on workflow/controller/dag.go
> +			if task := d.GetTask(depName); task.ContinuesOn(branchPhase, d.getTaskNode(depName).Outputs.ExitCode) {
Can you add test?

2021-09-12 23:05 UTC, sarabala1979 commented on workflow/controller/steps.go
> +		if childNode.FailedOrError() && !step.ContinuesOn(childNode.Phase, childNode.Outputs.ExitCode) {
Can you add test?

2021-09-21 16:54 UTC, alexec requested changes
Changes requested by Bala. Please dismiss this review once done.

2021-10-31 17:57 UTC, alexec requested changes
Please:

* [ ] Address @simster7 comments.
* [ ] Sync with master.
* [ ] Run `make pre-commit -B` and push changes.
* [ ] Dismiss reviews.

2022-01-08 21:43 UTC, closed without merging

2024-10-22 19:55 UTC, tooptoop4 commented
where @kriti-sc