feat: Add template node to pod name. Fixes #1319
argoproj/argo-workflows pull request #6712
Opened 2021-09-12 19:26 UTC by JPZ13

This PR is a continuation of Alex's PoC  #6647

2021-09-13 21:04 UTC, alexec commented on docs/environment-variables.md
> +| `USE_LEGACY_POD_NAMES` | `bool` | `false` | Whether to have pod names contain the template name (false) or be the node id (true). |
how about `POD_NAMES=v1` default is `v2`

2021-09-13 21:05 UTC, alexec commented on workflow/controller/node_counters_test.go
> +func testNodePodExists(t *testing.T, woc *wfOperationCtx) {
should be `Test` uppercase T

2021-09-13 21:06 UTC, alexec commented on workflow/controller/workflowpod.go
> +				common.AnnotationKeyNodeID:   nodeID, // TODO - test annotation is applied
TODO

2021-09-13 21:07 UTC, alexec commented on workflow/util/util.go
> +func PodName(workflowName, nodeName, templateName, nodeID string) string {
please put this func into own file

2021-09-13 21:07 UTC, alexec commented on workflow/util/util_test.go
> +func TestPodName(t *testing.T) {
own file

2021-09-13 21:08 UTC, alexec requested changes
some small changes

2021-09-13 21:35 UTC, alexec commented
LGTM. Passing to @sarabala1979 for him to review.

2021-09-13 21:35 UTC, alexec approved these changes

2021-09-15 18:03 UTC, alexec commented
@sarabala1979 I'm going to assume you're lack of reply means you are not able to review this. I'll merge.

2021-09-15 18:03 UTC, merged

2023-02-26 14:45 UTC, vivekthangathurai commented
I am using v3.2.8 and not seeing this behaviour.