feat: Add env vars config for argo-server and workflow-controller
argoproj/argo-workflows pull request #6767
Opened 2021-09-20 04:02 UTC by prichrd

This is a proposal for https://github.com/argoproj/argo-workflows/issues/5914. It uses https://github.com/spf13/viper to parse environment variables from the flag names.

2021-09-20 04:22 UTC, prichrd commented
Please let me know if this needs more tests.

2021-09-20 15:01 UTC, alexec commented
Looks good, so simple. Can we add some docs about this?

2021-09-20 15:20 UTC, prichrd commented
Sure thing, can you just point me to the doc I could update please?

2021-09-20 23:12 UTC, prichrd commented
I added a subsection in the https://github.com/argoproj/argo-workflows/blob/master/docs/environment-variables.md docs. 
I also fixed the linting issues blocking the CI.
Any hint as to why the CI is failing?

2021-09-21 17:05 UTC, alexec commented
I was wrong about where to add those flags. It fails `make codegen`. It also means that we need the keep that list up-to-date - which we will fail to do.

Instead, can I ask you to just add a bit like this:

```

Parameters can be specified as environment variables:

  workflow-controller --managed-namespace=argo

Can be expressed as:

  env MANAGED_NAMESPACE=argo workflow-controller
```

2021-09-21 17:05 UTC, alexec requested changes
Please dismiss review when done.

2021-09-21 17:16 UTC, prichrd commented
That makes total sense. I will update the environment.yaml doc to reflect that suggestion.

2021-09-22 03:40 UTC, alexec commented
Is it possible to have ARGO_ as prefix?

2021-09-22 19:28 UTC, prichrd commented
It shouldn't be an issue, it is fairly simple to do with Viper's `SetEnvPrefix` (https://pkg.go.dev/github.com/spf13/viper#SetEnvPrefix)  I'll fix that.

2021-09-22 21:26 UTC, prichrd commented
![image](https://user-images.githubusercontent.com/3706527/134424278-d4a1cc9b-dae1-49aa-a0f0-e324c8efd2a3.png)
@alexec, done!

2021-09-22 21:45 UTC, alexec approved these changes

2021-09-22 21:46 UTC, alexec commented
🚀

2021-09-22 22:03 UTC, merged