docs: patching workflow with labels example
argoproj/argo-workflows pull request #7060
Opened 2021-10-26 07:43 UTC by vidarlx

As there is an example how to patch a k8s pod with new **annotations**, it is a bit different in case of the **workflow** crd resource. 

I spent some time trying to patch a workflow with annotations (for easier searching by custom fields), used an example how to patch a pod, but ended up with "invalid request" errors from `kubectl` while trying to apply the patch during workflow run.
Turned out it needs `labels` instead of `annotations`. Kinda obvious, but not that easy to catch

✔️ Sign-off your commits to pass the DCO check: `git commit --signoff`.
✔️ Say how how you tested your changes. If you changed the UI, attach screenshots.
      I have run the example on my argo installation and then checked results in the UI, see the screenshoot below

![image](https://user-images.githubusercontent.com/2722691/138829963-cc39e389-a6a7-4ea6-8720-eb573f600c70.png)

2021-10-31 17:46 UTC, alexec requested changes
Please:
* [ ] Sync with master.
* [ ] Run `make pre-commit -B`.
* [ ] Push changes.
* [ ] Dismiss this review.

2021-11-01 15:24 UTC, alexec submitted a review, later dismissed
Need to run `make pre-commit -B` to fix the codegen job.

2021-11-03 06:54 UTC, vidarlx commented
> Need to run `make pre-commit -B` to fix the codegen job.

Sorry, I'm unable to run this check. I experience the same issues as authors of [this PR](https://github.com/argoproj/argo-workflows/pull/5797) and [this issue](https://github.com/argoproj/argo-workflows/issues/2245), I tried to fix it on my end, did some manual work but got segfault when it finally resolved all required imports.

2021-11-03 15:12 UTC, alexec commented
An alternative is to copy the diffs printed in the codegen job and use “git apply” to apply them.

2021-11-03 20:00 UTC, vidarlx commented
> An alternative is to copy the diffs printed in the codegen job and use “git apply” to apply them.

Applied the diff from the failed job, so it added the yaml file to `docs/fields.md`. Not sure if this is what you meant, so please request changes again if I understood the comment wrong

2021-11-08 06:57 UTC, vidarlx commented
Btw @alexec I can't dismiss the review as usual (no button there), probably due to force-push 
![image](https://user-images.githubusercontent.com/2722691/140697255-1d5321d0-85c9-4ea1-9a92-fde8c92dde97.png)

2021-12-17 17:50 UTC, terrytangyuan reviewed
Could you resolve the conflicts?

2021-12-17 20:32 UTC, vidarlx commented
> Could you resolve the conflicts?

Done

2021-12-19 00:28 UTC, terrytangyuan approved these changes

2021-12-19 00:28 UTC, merged