feat(controller): Added new workflow and Prometheus metric state. Fixes #7036
argoproj/argo-workflows pull request #7096
Opened 2021-10-29 10:22 UTC by florianpaulhoberg

# Summary

This PR adds a new workflow & Prometheus metric state 'Terminated' for terminated workflows (as req. in #7036).
When terminating a workflow in argo-workflows this should be correctly represented within the Prometheus metrics. In the current state this will not be handled as a dedicated state. IMHO a user terminated workflow should not be treated as a failed one. Therefore, a new gauge for Prometheus should be integrated to provide this.

# Use Cases

The current overview of human terminated workflows can be misleading. It should be directly visible that a workflow was terminated manually by a human interaction and it was expected that this workflow could not terminate in a successful way. This will be more important when It comes to monitoring and alerting with Prometheus/Grafana setups where terminated workflows should not raise any alerts.

# Tests
This has been tested on release/3.2 in a test setup with a modified Grafana dashboard where it was possible to see terminated Workflows. These ones will not more be displayed as failed ones.

2021-10-30 18:41 UTC, florianpaulhoberg commented
Adding additional metrics with labels/annotations will not change the workflow state itself. This software is about running a bunch of workflows and the correct handling of it is important when it comes to monitoring and alerting. I think the WF still gets classified as 'failed' even if you have an additional metric of terminated ones. 

Imagine you're on pager duty and someone in another timezone terminates the job for any reason. The WF gets classified as 'failed' and exported as a metric and triggers an alert for someone on a pager duty.

2021-10-30 18:53 UTC, alexec commented
Isn't a workflow that runs too long a failed workflow? When know it failed to complete its work because it did not exit gracefully.

2021-10-31 07:38 UTC, florianpaulhoberg commented
In our setup it may often come to user terminated WFs within the GUI (e.g. someone finds wrong VARs, wrong WF type, etc. just after submitting a WF or on scheduled ones that it may not be necessary to block the resources right, now). When such a WF gets terminated it needs to be handled correctly to avoid any further alerts that are generated based on the metrics (e.g. involving someone on pager duty to let her/him sleep).

2021-10-31 15:58 UTC, alexec commented
I think I could be persuaded round. GitHub actions has “cancelled “ state which is very similar.

2021-10-31 15:59 UTC, alexec commented
Could you come to the weekly meeting on Tuesday?

2021-11-02 09:15 UTC, florianpaulhoberg commented
I try to join, unfortunately it may be that I'm still in a customer call at this time. Maybe you can highlight this topic in case that I'm absent.

2021-11-02 17:50 UTC, alexec reviewed
Myself and @jessesuen do no think we can introduce a new state as we will have many users that will assume workflow state machine and it will break them, so that is not an option.

Our suggestion is to add a label to the prometheus metric than indicates if the workflow was terminated. This would be to this variable:

https://github.com/argoproj/argo-workflows/blob/6f26fb0638c6576d575af2bf94be86fc8b6d4856/workflow/metrics/metrics.go#L49

2021-11-03 15:26 UTC, alexec requested changes
changes requested

2021-11-03 15:31 UTC, florianpaulhoberg commented
I take a look if this is a suitable way for us and may provide an updated PR if it fits the needs.

2022-01-16 06:49 UTC, closed without merging