fix(controller): dag and steps with unresolved with.params field. Fixes #7094
argoproj/argo-workflows pull request #7110
Opened 2021-10-30 18:04 UTC by ziv-codefresh

Signed-off-by: ziv-codefresh <ziv@codefresh.io>

Don't bother creating a PR until you've done this:

* [ ] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

2021-10-31 08:27 UTC, ziv-codefresh commented
@alexec @sarabala1979 PTAL. thanks!

2021-10-31 16:02 UTC, alexec commented
Unresolved should be error. Empty should be skip?

2021-10-31 16:15 UTC, ziv-codefresh commented
@alexec ive updated the description with additional information. 
`expandStep/expandTask` running before `shouldExecute` function. means that regardless if the step will eventually run we are trying to parse withParam field. 
so at this point we dont know if the step will run or not.. 
the issue is the following:
``when you create a workflow with "withParam" provided by a previous steps, if you skip both steps, the workflow fail instantly with this error``

with the change i suggested the step will be skipped rather than failed. 

the only solution i can think of is somehow is to check the parameters after we verify the step actually need to run. but im not sure what changes it will require. WDYT?

2021-10-31 17:20 UTC, alexec reviewed
> expandStep/expandTask running before shouldExecute function. 

Can we swap them around?

2021-10-31 18:18 UTC, ziv-codefresh commented
i guess it is possible because all the steps/tasks that will be created (after the expending according to the `withParam` `WithItems` and `WithSequence`) will have the same when condition (correct me if im wrong).
so potentially we can check the when condition before we are expending them and only if its fulfilled we will continue to the actual expending, it will require some refactor in the `executeStepGroup` and `executeDAGTask`

2021-11-01 14:56 UTC, simster7 requested changes
In my opinion this change, even though it's a simple reordering, has a large surface exposure and should be carefully implemented and reviewed

2021-11-01 14:56 UTC, simster7 commented on workflow/controller/steps.go
> +		childNodeName := fmt.Sprintf("%s.%s", sgNodeName, step.Name)
This should not be generated independently in two spots. If anything, this should be extracted into a helper function.

2021-11-01 14:56 UTC, simster7 commented on workflow/controller/steps.go
> +	stepTemplateScope := stepsCtx.tmplCtx.GetTemplateScope()
Why lose the comment on this line?

2021-11-01 14:56 UTC, simster7 commented on workflow/controller/dag.go
> +	if node == nil {
I'm not comfortable with the refactor in this file. I don't think we should have so much (critical) logic controlled by nested if else statements. Is there a way to refactor it such that the `shouldExecute` check happens outside in its own block? Is it possible to have it as a normal block before the `expandedTasks, err := expandTask(*newTask)` line as it currently exists on the master branch?

2021-11-01 16:02 UTC, sarabala1979 commented
@ziv-codefresh it should fix in `ProcessArgs` if any variable is not resolved or substituted, it should take the default value.
If the default value is not configured, the workflow should fail with `not supplied`

2021-11-01 16:08 UTC, ziv-codefresh commented
@sarabala1979 @simster7 sorry guys its not ready to review.
i had conversion above it @alexec and i suggest some solution and opened the pr but seems its not the correct approach.

its just some WIP that i tried to refactor it but its far from be ready. ill mark this as a draft. sorry for that.

2021-11-01 16:18 UTC, sarabala1979 commented
@ziv-codefresh no issues. I think this should be fixed globally.  Currenly `withParam` is failling because of variable is not substituted others will just print the actual variable string `{{xxx}}`.  `SubstituteParams` is allowing the unresolved variables `, err := template.Replace(globalReplacedTmplStr, replaceMap, true)`. 

Suggestion:
  if any variable is not resolved or substituted, it should take the default value.
If the default value is not configured, the workflow should fail with not supplied.

2021-11-01 16:32 UTC, ziv-codefresh commented
@sarabala1979 sounds good. so you are suggesting that every substation will use the `ProcessArgs` method? 
btw, i dont think it will solve the issue which raised here, the issue is the following:
`when you create a workflow with "withParam" provided by a previous steps, if you skip both steps, the workflow fail instantly`
so basically if im expecting that step X will run and then step Y and step Y use the output of X , so even if both of the steps should be skipped, it will failed in the phase of expanding (in case the user will did not set any default value) 
am i missing something?

2021-11-02 03:09 UTC, sarabala1979 commented
@ziv-codefresh you are trying to add logic if the current step is referring previous step variable and the previous step is skipped/didn't run.  workflow should fail. Am I getting correctly?

2021-11-02 06:53 UTC, ziv-codefresh commented
@sarabala1979 actually no, if the current step is running and referring previous step variable and the previous step is skipped/didn't run the workflow will fail (as expected).
the issue is when the current step should not run (because his when condition is not fulfilled) and this step referring previous step variable and the previous step is skipped/didn't run the workflow will fail and this is wrong behaviour.
the reason that the workflow will fail in this case is because we are trying to expand the task before we are checking if the step should run. so basically what happens is that we are failing the all workflow because we are enable to resolve the withParams field for a step that will not run at all.
to solve this, we need first of all to check if the step should run, and only if he should run we need to apply the expand logic.
by changing this we will get the following:
if B is running and referring to step A variable and step A is skipped/didn't run the workflow will fail (As today).
if B should should be skipped and referring to step A variable and step A is skipped/didn't run the workflow will not fail and step B will be skipped.
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-param-result-
spec:
  arguments:
    parameters:
      - name: get-list
        value: false
  entrypoint: loop-param-result-example
  templates:
  - name: loop-param-result-example
    steps:
    - - name: generate
        when: "{{ workflow.parameters.get-list}} == true"
        template: gen-number-list
    - - name: sleep
        when: "{{ workflow.parameters.get-list}} == true" 
        
        template: sleep-n-sec
        arguments:
          parameters:
          - name: seconds
            value: "{{item}}"
        withParam: "{{steps.generate.outputs.result}}"
```
today, this workflow will fail because `steps.generate.outputs.result` will not be resolved (generate step will be skipped)
but also `sleep` should be skipped and there is no reason the workflow will failed.
swapping the logic of `shouldExecute` and `expandTask` should solve it, because we first of all check if the step should run, and only if it is we run the expand logic. 
i hope it more clear now.

2021-11-02 11:30 UTC, ziv-codefresh commented
@alexec @sarabala1979 @simster7 so i tried to swap the `shouldExecute` and `expandTask/expandDag` functions, but i dont see how it can work. 
`shouldExecute` function needs a substituted when expression to decide whether or not a step should execute, and the `expandTask/expandDag` needs to know if the step actually need to run in order to perform the substation.
so its kind of `chicken egg` problem here and im not sure what can be done. 
example for problematic template 
```
....
    - - name: divide-by-2
        template: divide-by-2
        arguments:
          parameters:
          - name: num
            value: "{{item.num}}"
        withParam: "{{steps.odd-or-even.outputs.parameters}}"
        when: "{{item.evenness}} == even"
...

```
so in order to calculate the when condition we need to resolve `{{steps.odd-or-even.outputs.parameters}}` field.
but in order to decide if we need to resolve `{{steps.odd-or-even.outputs.parameters}}` we need to calculate then when condition.

2021-11-04 06:35 UTC, ziv-codefresh commented
@alexec @sarabala1979 i would appreciate if you can take a quick look here.

> @alexec @sarabala1979 @simster7 so i tried to swap the `shouldExecute` and `expandTask/expandDag` functions, but i dont see how it can work. `shouldExecute` function needs a substituted when expression to decide whether or not a step should execute, and the `expandTask/expandDag` needs to know if the step actually need to run in order to perform the substation. so its kind of `chicken egg` problem here and im not sure what can be done. example for problematic template
> 
> ```
> ....
>     - - name: divide-by-2
>         template: divide-by-2
>         arguments:
>           parameters:
>           - name: num
>             value: "{{item.num}}"
>         withParam: "{{steps.odd-or-even.outputs.parameters}}"
>         when: "{{item.evenness}} == even"
> ...
> ```
> 
> so in order to calculate the when condition we need to resolve `{{steps.odd-or-even.outputs.parameters}}` field. but in order to decide whether or not to resolve `{{steps.odd-or-even.outputs.parameters}}` we need to calculate the `when` condition.

2022-01-16 06:49 UTC, closed without merging