feat(controller): Log expression context for conditional retries.
argoproj/argo-workflows pull request #7181
Opened 2021-11-08 05:22 UTC by jmcarp

I was debugging an issue with conditional retries, and it took a while to figure out that a certain failure mode was associated with an exit code of `-1`. Logging the expression context would help with this kind of task in the future. Let me know if there's a better place to put this than the operator logs!

cc @jli

Signed-off-by: Josh Carp <jm.carp@gmail.com>

Don't bother creating a PR until you've done this:

* [ ] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

2021-11-08 05:26 UTC, jmcarp commented
It might also be useful to expose the node's exit code in `NodeStatus`. I can look at that in addition to or instead of this change--let me know what you all think.

2021-11-09 17:18 UTC, jmcarp commented
By the way, I'm still confused about why preempted pods have no outputs or exit code. Here's an example from my testing:

```
   retry-test-preempt-01-3853357172:
      displayName: retry-test-preempt-01(1)
      finishedAt: null
      hostNodeName: ...
      id: retry-test-preempt-01-3853357172
      message: Node is shutting, evicting pods
      name: retry-test-preempt-01(1)
      phase: Failed
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 0
      startedAt: "2021-11-07T07:13:40Z"
      templateName: retry-crash
      templateScope: local/retry-test-preempt-01
      type: Pod
```

2021-11-23 01:23 UTC, alexec commented
Can you please add the output of this change?

2021-11-23 20:24 UTC, alexec requested changes
info requested

2021-12-10 07:04 UTC, sarabala1979 approved these changes

2022-01-11 01:46 UTC, kennytrytek commented
I attempted to generate log output for this issue, but it appears that using `expression` in a retry strategy is currently broken. I filed a bug for that issue here: https://github.com/argoproj/argo-workflows/issues/7539

Until that is resolved, I do not know of a good way to show this output as requested.

2022-01-19 15:46 UTC, alexec commented on workflow/controller/operator.go
> +		woc.log.WithField("node", node.Name).Infof("evaluating retry conditional with scope %s", localScope)
Should be Debug level?

2022-02-12 18:22 UTC, closed without merging

2024-10-22 19:43 UTC, tooptoop4 commented
where @jmcarp