feat: Add PodPriorityClassName to SubmitOpts. Fixes #7059
argoproj/argo-workflows pull request #7274
Opened 2021-11-24 14:12 UTC by nmandery

Fixes #7059. 

I tested these changes using the development setup described in https://github.com/argoproj/argo-workflows/blob/master/docs/running-locally.md.

Signed-off-by: Nico Mandery <nico@nandery.net>

Don't bother creating a PR until you've done this:

* [x] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

2021-11-26 06:43 UTC, nmandery commented
According to the PR-template PRs should stay as draft until all checks pass. As me being a first-time contributor, CI-checks are disabled for this PR. Could one maintainer please approve the workflows here? Thanks a lot ;)

2021-11-26 14:33 UTC, nmandery commented
Thanks for enabling the CI 👍

2021-11-29 18:14 UTC, alexec requested changes
needs a test

2021-11-29 18:14 UTC, alexec commented on workflow/util/util.go
> +	if opts.PodPriorityClassName != "" {
this needs a test

2021-11-30 16:27 UTC, merged