feat: adjust name of generated Python SDK
argoproj/argo-workflows pull request #7328
Opened 2021-12-02 14:35 UTC by flaviuvadan

This PR adds configurations to the OpenAPI generator so that the generated Python SDK uses `argo-workflows` as the name rather than `openapi-client`.

Issue: #7248

2021-12-02 14:40 UTC, terrytangyuan reviewed
Can you make sure the generated SDK works as expected besides the known issue? https://github.com/argoproj/argo-workflows/issues/7293

2021-12-02 14:40 UTC, terrytangyuan commented on sdks/python/Makefile
> +publish:
This was there for testing in the CI: https://github.com/argoproj/argo-workflows/blob/master/.github/workflows/sdks.yaml#L20

2021-12-02 14:40 UTC, terrytangyuan commented on sdks/python/Makefile
> +	rm -rf $(WD)/.gitlab-ci.yml $(WD)/.travis.yml $(WD)/git_push.sh
Not needed since we have explicitly gitignored them?

2021-12-02 16:00 UTC, alexec commented
You need to run `make pre-commit -B`

2021-12-08 00:04 UTC, alexec requested changes
Please run `make pre-commit -b` and commit the changes. We should then be good to go.

2021-12-08 14:33 UTC, terrytangyuan requested changes
Could you update the examples in README and the examples folder?

2021-12-08 15:21 UTC, terrytangyuan approved these changes

2021-12-08 19:21 UTC, merged