feat: made workflow.labels and workflow.annotations exposable as JSON string
argoproj/argo-workflows pull request #7397
Opened 2021-12-13 23:14 UTC by dpadhiar

Don't bother creating a PR until you've done this:

* [ ] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

2021-12-13 23:32 UTC, sarabala1979 approved these changes

2021-12-14 00:01 UTC, simster7 requested changes
Duplicate of https://github.com/argoproj/argo-workflows/pull/7396?

2021-12-14 00:01 UTC, simster7 commented
@NikeNano

2021-12-17 18:08 UTC, sarabala1979 commented
I will close this PR @dpadhiar is working. with PR owner.

2021-12-17 18:08 UTC, closed without merging