add retry when kill container and ignore error when kill sidecar failed
argoproj/argo-workflows pull request #7404
Opened 2021-12-14 06:33 UTC by henrywangx

Since sometimes the connection between the APIServer is not stable. We don't want to rerun for this case.
So add retry to APIServer.

* [X] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

2021-12-14 13:52 UTC, terrytangyuan commented on util/errors/errors.go
> +		strings.Contains(err.Error(), "request did not complete within requested timeout") {
Perhaps reuse `matchTransientErrPattern`?

2021-12-14 13:53 UTC, terrytangyuan commented on workflow/executor/k8sapi/client.go
> +		exec, err := common.ExecPodContainer(c.config, c.namespace, c.podName, container.Name, true, true, command...)
Reuse https://github.com/argoproj/argo-workflows/blob/54007e1644b7678aebbf28ed3c4666939415bc53/workflow/executor/executor.go#L45-L57?

2021-12-15 05:17 UTC, henrywangx commented on workflow/executor/k8sapi/client.go
> +		exec, err := common.ExecPodContainer(c.config, c.namespace, c.podName, container.Name, true, true, command...)
Done

2021-12-15 16:07 UTC, terrytangyuan commented on cmd/argoexec/commands/wait.go
> +		err := wait.ExponentialBackoff(executor.ExecutorRetry, func() (bool, error) {
Use `waitutil.Backoff`

2021-12-15 16:08 UTC, terrytangyuan commented on cmd/argoexec/commands/wait.go
> +			return true, nil
Should we only retry on transient errors, e.g. ``errorsutil.IsTransientErr``?

2021-12-15 16:08 UTC, terrytangyuan commented on cmd/argoexec/commands/wait.go
> +		err := wait.ExponentialBackoff(executor.ExecutorRetry, func() (bool, error) {
Example: https://github.com/argoproj/argo-workflows/blob/69ff67b02c1af53582c39b1db574a3a525f6d49c/workflow/executor/executor.go#L615-L622

2021-12-17 17:51 UTC, terrytangyuan commented
Please fix the failing builds.

2021-12-20 02:13 UTC, henrywangx commented
> Please fix the failing builds.

Done

2022-01-19 16:02 UTC, alexec commented
@terrytangyuan ready to re-review?

2022-01-20 14:40 UTC, terrytangyuan requested changes

2022-01-20 14:40 UTC, terrytangyuan commented on workflow/executor/k8sapi/client.go
> +		}
We probably only want to retry for transient errors?

2022-01-20 14:40 UTC, terrytangyuan commented on cmd/argoexec/commands/wait.go
> +		retryCnt := 0
We currently don't have retry counter in other places. It might be better to add later in all places where we are retrying.

2022-02-10 07:03 UTC, henrywangx commented
@terrytangyuan I have removed `retryCnt`. But I found the master branch has changed a lot, I can't fix the CI. Just close this PR please.

2022-02-10 07:04 UTC, closed without merging

2024-10-22 19:34 UTC, tooptoop4 commented
where @henrywangx

2024-10-22 22:33 UTC, agilgur5 commented
> where @henrywangx

The `kill` command will [get re-queued](https://github.com/argoproj/argo-workflows/blob/bb5130e841ab02cfe5b65f19c214fe309ca88bce/workflow/controller/controller.go#L617) these days if it fails, so this is no longer necessary