fix: out of range in MustUnmarshal
argoproj/argo-workflows pull request #7485
Opened 2022-01-03 11:12 UTC by AdamKorcz

This adds a more readable and easier recoverable message for the case when the input is of length 0. 

This was reported by OSS-fuzz.

2022-01-03 15:31 UTC, terrytangyuan requested changes
Thanks! Could you add a test case and perhaps a link to the report?

2022-01-04 11:38 UTC, AdamKorcz commented
> Could you add a test case and perhaps a link to the report?

done

2022-01-04 13:01 UTC, AdamKorcz commented
It looks like the CI is failing with something unrelated:

```
--- FAIL: TestSynchronizationWithStepRetry (0.02s)
    operator_concurrency_test.go:754: 
        	Error Trace:	operator_concurrency_test.go:754
        	Error:      	Not equal: 
        	            	expected: "Error"
        	            	actual  : "Failed"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-(v1alpha1.NodePhase) (len=5) "Error"
        	            	+(v1alpha1.NodePhase) (len=6) "Failed"
        	            	 
        	Test:       	TestSynchronizationWithStepRetry
```
Will rerun the CI later.

2022-01-04 14:22 UTC, terrytangyuan approved these changes

2022-01-04 15:40 UTC, terrytangyuan requested changes
Please also fix the lint check

2022-01-05 15:41 UTC, terrytangyuan approved these changes

2022-01-05 15:41 UTC, merged

2022-01-05 15:42 UTC, terrytangyuan commented
@AdamKorcz Is there a link to the new report that reflects this fix?

2022-01-05 15:44 UTC, AdamKorcz commented
Thanks. The OSS-fuzz issue should resolve automatically during the next build which will most likely be sometime within 24 hours.

2022-01-05 15:45 UTC, terrytangyuan commented
> 

Sounds good. Thanks!