feat: Update new version modal for v3.3. Fixes #7639
argoproj/argo-workflows pull request #7707
Opened 2022-01-31 15:53 UTC by alexec

Signed-off-by: Alex Collins <alex_collins@intuit.com>

Don't bother creating a PR until you've done this:

* [ ] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

2022-01-31 15:58 UTC, terrytangyuan approved these changes

2022-01-31 15:59 UTC, terrytangyuan commented on ui/src/app/modals/new-version/new-version-modal.tsx
> +                        Debug pause
Consistency: Debug -> debug

2022-02-07 19:49 UTC, terrytangyuan requested changes
The linked docs do not exist and are not ready yet.

2022-02-14 23:35 UTC, alexec commented
2 weeks old. Not going to wait for docs anymore.

2022-02-14 23:36 UTC, terrytangyuan approved these changes

2022-02-14 23:52 UTC, merged