fix: submitting Workflow from WorkflowTemplate will set correct serviceAccount and securityContext - fixes #7726
argoproj/argo-workflows pull request #7805
Opened 2022-02-08 01:13 UTC by dpadhiar

fixes #7726 

Previously if a user started a Workflow from a WorkflowTemplate using the CLI, the serviceAccount and securityContext was not set based upon the StoredWorkflowSpec like is expected. Now, when serviceAccount and securityContext are checked for in `get.go`, `GetExecSpec()` is run to check if `wf.Status.StoredWorkflowSpec` is set or not. If so, it will reference this spec instead as expected.

Example WorkflowTemplate:

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-workflow-template-test
  namespace: argo
spec:
  entrypoint: main
  securityContext:
    runAsNonRoot: false
  serviceAccountName: argo
  templates:
    - name: main
      metadata:
      container:
        command:
          - bash
          - -c
          - echo 'Hello from WT'; env; sleep 15
        image: ubuntu
        name: main
```

Submitting through CLI:
```
dist/argo submit --from workflowtemplate/my-workflow-template-test --watch
```

Output:
```
Name:                my-workflow-template-test-5ppq9
Namespace:           argo
ServiceAccount:      argo
Status:              Succeeded
Conditions:          
 PodRunning          False
 Completed           True
Created:             Mon Feb 07 15:18:53 -0800 (20 seconds ago)
Started:             Mon Feb 07 15:18:53 -0800 (20 seconds ago)
Finished:            Mon Feb 07 15:19:13 -0800 (now)
Duration:            20 seconds
Progress:            1/1
ResourcesDuration:   32s*(1 cpu),25s*(100Mi memory)

STEP                                TEMPLATE  PODNAME                          DURATION  MESSAGE
 ✔ my-workflow-template-test-5ppq9  main      my-workflow-template-test-5ppq9  19s 
```

2022-02-08 01:18 UTC, alexec requested changes
when I did triage on this, I thought there was a third place in the cli where `wf.Spec` needs to be replaced by `wf.GetExecSpec()`, can you check please?

2022-02-08 01:18 UTC, alexec commented on cmd/argo/commands/get.go
> +		if wf.Spec.WorkflowTemplateRef != nil {
I think this can be simpler, just say "unset"

2022-02-08 01:18 UTC, alexec commented on pkg/apis/workflow/v1alpha1/workflow_types_test.go
> +	wf := Workflow{
add a second test when stored spec is nil

2022-02-08 16:44 UTC, dpadhiar commented
> when I did triage on this, I thought there was a third place in the cli where `wf.Spec` needs to be replaced by `wf.GetExecSpec()`, can you check please?

In `get.go` on lines 160 - 168, the spec is used here to access parameters. I believe this may be the third place for a CLI change, could you confirm?

```
if len(wf.Spec.Arguments.Parameters) > 0 {
		out += fmt.Sprintf(fmtStr, "Parameters:", "")
		for _, param := range wf.Spec.Arguments.Parameters {
			if param.Value == nil {
				continue
			}
			out += fmt.Sprintf(fmtStr, "  "+param.Name+":", *param.Value)
		}
	}
	
```

2022-02-08 16:46 UTC, alexec commented
> > when I did triage on this, I thought there was a third place in the cli where `wf.Spec` needs to be replaced by `wf.GetExecSpec()`, can you check please?
> 
> In `get.go` on lines 160 - 168, the spec is used here to access parameters. I believe this may be the third place for a CLI change, could you confirm?
> 
> ```
> if len(wf.Spec.Arguments.Parameters) > 0 {
> 		out += fmt.Sprintf(fmtStr, "Parameters:", "")
> 		for _, param := range wf.Spec.Arguments.Parameters {
> 			if param.Value == nil {
> 				continue
> 			}
> 			out += fmt.Sprintf(fmtStr, "  "+param.Name+":", *param.Value)
> 		}
> 	}
> 	
> ```

Yes. Fix that too.

2022-02-09 00:46 UTC, alexec approved these changes
🚀 LGTM

2022-02-09 00:46 UTC, merged