feat: remove pod workers. Fixes #4090
argoproj/argo-workflows pull request #7837
Opened 2022-02-09 14:56 UTC by isubasinghe

Signed-off-by: Isitha Subasinghe <isitha@pipekit.io>
This removes the pod workers and the pod queue and directly writes into the workflow queue instead. 
Fixes #4090

2022-02-09 15:42 UTC, JPZ13 commented
@isubasinghe - I don't have access to push a commit to this pull request, but here's how to fix the linting error: https://github.com/pipekit/argo-workflows/blob/remove-pod-workers/workflow/controller/controller.go#L1033

2022-02-10 18:07 UTC, alexec requested changes

2022-02-10 18:07 UTC, alexec commented on workflow/controller/controller.go
> +					log.WithError(err).Warnf("could not enqueue workflow from pod label on add: %s", err)
do not use `Warnf`, it is not structured, please use `Warn`

2022-02-11 00:35 UTC, alexec commented
I think we need one more change. In docs/upgrading.md, we should mention that this flag has been removed. So users may have custom configured it.

2022-02-11 01:12 UTC, alexec approved these changes

2022-02-11 01:17 UTC, merged