feat: Support loading manifest from artifacts for resource templates
argoproj/argo-workflows pull request #7980
Opened 2022-02-23 08:57 UTC by book987

Signed-off-by: book987 <book78987book@gmail.com>

Fixes #5878

2022-02-23 15:48 UTC, alexec commented on workflow/controller/workflowpod.go
> +	if len(tmpl.Inputs.Artifacts) > 0 || tmpl.GetType() == wfv1.TemplateTypeScript || tmpl.GetType() == wfv1.TemplateTypeResource || woc.getContainerRuntimeExecutor() == common.ContainerRuntimeExecutorE
I think we should probably remove this check completely and always run the init container. But not in the PR. Tech debt.

2022-02-23 15:48 UTC, alexec commented on workflow/executor/executor.go
> +			return nil
If path is empty maybe return an error?

2022-02-25 20:46 UTC, terrytangyuan requested changes

2022-02-25 20:46 UTC, terrytangyuan commented on workflow/executor/executor.go
> +		if we.Template.Resource.ManifestFrom != nil {
We should log something similar to what we did above:
```
	case wfv1.TemplateTypeScript:
		log.Infof("Loading script source to %s", common.ExecutorScriptSourcePath)
```

2022-02-25 20:46 UTC, terrytangyuan commented on test/e2e/resource_template_test.go
> +          path: /tmp/manifest.yaml
I don't see `manifestFrom` being used anywhere in the implementation so I don't think path other than `/tmp/manifest.yaml` works.

2022-04-14 14:52 UTC, alexec commented
@book987 how's it going? Do you want any help or support?

2022-05-02 00:30 UTC, closed without merging

2022-05-04 18:17 UTC, terrytangyuan commented
Would you like to re-open this PR and fix the CI?

2022-05-04 18:29 UTC, book987 commented
> Would you like to re-open this PR and fix the CI?

Yeah but I don't know how to do this, could you help me? I've never done that.

2022-05-04 19:07 UTC, terrytangyuan commented
Somehow I am not able to re-open this PR. @alexec Do you see the same?

2022-05-04 19:08 UTC, terrytangyuan commented
Perhaps create a new PR then

2022-05-06 09:18 UTC, RoryDoherty commented
@book987 if you're too busy to finish this then I would be happy to pick this up, Let me know?
I'm currently running into this issue myself and would like to see it fixed

2022-05-06 13:14 UTC, book987 commented
> @book987 if you're too busy to finish this then I would be happy to pick this up, Let me know? I'm currently running into this issue myself and would like to see it fixed

Hi I've just create a new PR #8657 with new change. Can I ask you to help review the code? CI has passed.

cc @terrytangyuan