Fixes #
argoproj/argo-workflows pull request #8114
Opened 2022-03-09 20:33 UTC by prithvihv

Fixes #TODO

When creating your PR: 

* Make sure that "Fixes #" is in both the PR title (for release notes) and description (to automatically link and close the issue).
* Say how you tested your changes. If you changed the UI, attach screenshots.
* Set your PR as a draft initially.
* Your PR needs to pass the required checks before it can be approved. 
* Once required tests have passed, mark your PR "Ready for review".

If changes were requested, once you've made them, you MUST dismiss the review to get it reviewed again.

-->

2022-03-09 20:34 UTC, prithvihv commented
sorry, didn't mean to mark the PR to be ready for review

2022-03-09 20:40 UTC, prithvihv commented
@blkperl in the PR description template, it mentions to run `--sign-off`, in the newer versions of git this flag has been changed to `--signoff`. Can consider changing this

2022-03-09 23:16 UTC, blkperl commented
@prithvihv Do you mean the `sign-off` flag here? https://github.com/argoproj/argo-workflows/blob/master/.github/pull_request_template.md?plain=1#L19 

Would you like to open a PR to update that?

2022-03-09 23:29 UTC, blkperl reviewed
Upon closer inspection of the deprecation notice. I'm not sure we can drop the library yet as the go client still depends on it. The change in this PR removes test coverage that I think we want to keep. 

https://github.com/prometheus/client_model#deprecation-note


> The [Go instrumentation library](https://github.com/prometheus/client_golang), however, has been built around the protobuf-based data model. As a byproduct thereof, it is still able to expose the protobuf-based exposition format. The Go instrumentation library is the only remaining repository within the [Prometheus GitHub org](https://github.com/prometheus) directly using the prometheus/client_model repository.

2022-03-10 03:54 UTC, prithvihv commented
@blkperl can we close the issue and this pr then?

2022-03-10 18:08 UTC, simster7 requested changes
Not sure removing tests is an acceptable consequence of removing this library?

2022-03-10 18:08 UTC, simster7 commented on go.mod
> +	github.com/prometheus/client_model v0.2.0 // indirect
Seems like library is still depended on regardless?

2022-03-10 21:54 UTC, blkperl commented
@prithvihv yeah we can close both for now until the upstream library provides a path forward.

2022-03-10 21:54 UTC, closed without merging