Allow optional space for param detection
argoproj/argo-workflows pull request #8867
Opened 2022-05-26 21:34 UTC by RyanCopley

Really, I intend for this to be more of a discussion than anything.

I work for a company that has a large argo workflow, and we've been struggling to reconcile strange behaviors around the space needed for the interpolated variables. I believe this is because this specific regex is not meeting the contract that was documented, and does not allow for those additional white space between the bracket and variable.

https://github.com/argoproj/argo-workflows/blob/master/docs/variables.md#simple

> Simple tags may have white-space between the brackets and variable.

https://github.com/argoproj/argo-workflows/blob/master/util/template/simple_template.go#L13 provides that contract, however, there is a code path during `argo lint` that tries to use the file i'm changing to determine if it is or isn't a parameter, in order to detect if it should allow that as a "global" param, but it doesn't follow that same contract?

https://github.com/argoproj/argo-workflows/blob/master/workflow/validate/validate.go#L872

I posted about this in the slack:

https://cloud-native.slack.com/archives/C01QW9QSSSK/p1653497167145119

https://cloud-native.slack.com/archives/C01QW9QSSSK/p1653600495901169

2022-05-27 15:16 UTC, tczhao commented
related https://github.com/argoproj/argo-workflows/issues/4286

2022-05-27 15:47 UTC, tczhao requested changes
A few things:

We'd better move this to an issue if its intended for discussion
For the PR. Can you fix the DCO, see [link](https://github.com/argoproj/argo-workflows/pull/8867/checks?check_run_id=6616955074) or `git commit -s --amend`

There seems more cases where this white space thing is not respected, e.g. https://github.com/argoproj/argo-workflows/blob/master/workflow/validate/validate.go#L1270. I'd probably start with searching all the `{{` codes...

We need to add more test to validate these edge cases

2022-05-31 02:14 UTC, sarabala1979 commented on workflow/validate/validate.go
> -	paramRegex               = regexp.MustCompile(`{{[-a-zA-Z0-9]+(\.[-a-zA-Z0-9_]+)*}}`)
Can you add  test?

2022-05-31 15:17 UTC, RyanCopley commented
I don't intend to come across as rude, but unfortunately my schedule doesn't allow me to put more effort into this when, now that I did this analysis, we have a way forward avoiding this problem. That means I have no interest (read: time, motivation) in any further commits to this PR to bring it up to your standards. I simply wish to let you all know that this contract is being broken, and a very thin example of what the issue is so you can understand and prioritize it on your own.

Good luck though, this issue was incredibly hard to wrap my head around and has led to toil on my team :(  For the record, we'll be standardizing on wether or not to allow spaces in these tags, and update our existing workflows accordingly.

2022-06-11 02:36 UTC, alexec commented
No more work expected on this PR. Closing.

2022-06-11 02:36 UTC, closed without merging

2024-10-22 10:56 UTC, tooptoop4 commented
/reopen

2024-10-23 16:32 UTC, agilgur5 commented
I believe this was superseded by #11781 and perhaps some PRs before it