docs: restore work-avoidance page
argoproj/argo-workflows pull request #9178
Opened 2022-07-19 10:17 UTC by mikutas

Signed-off-by: mikutas <23391543+mikutas@users.noreply.github.com>

Fixes #TODO

2022-07-20 18:07 UTC, juliev0 commented on docs/work-avoidance.md
> +
"you want to be able to resubmit"

2022-07-20 18:08 UTC, juliev0 commented on docs/work-avoidance.md
> +
nitpick: replace comma with semi-colon or period

2022-07-20 18:08 UTC, juliev0 commented on docs/work-avoidance.md
> +
and remove "on"

2022-07-20 18:26 UTC, juliev0 commented
It appears this is where it happened: https://github.com/argoproj/argo-workflows/commit/c2f450622d93dd18ddcba8aee85543b9d020a831#diff-cb9fc269fdf9cc076fc7f14092fe63f69f0275d24e3d2e8b41c8f1ce01b3314b

There was a reorganization to the page so I think it must have accidentally been removed then. (let us know if you see anything else this might have happened to there)

By the way, your Lint error should be fixed in master now.

2022-07-20 18:27 UTC, juliev0 requested changes
commented on some minor typos

2022-07-21 15:18 UTC, terrytangyuan approved these changes

2022-07-21 15:18 UTC, merged