Update delete.go
argoproj/argo-workflows pull request #9264
Opened 2022-07-31 09:58 UTC by Amirioelmos

Fixes #TODO

2022-08-02 16:39 UTC, sarabala1979 submitted a review, later dismissed

2022-08-02 16:40 UTC, sarabala1979 commented
@Amirioelmos Please fix DCO and codegen "make codegen -B"

2022-08-09 21:55 UTC, juliev0 requested changes
This is a duplicate PR from the other one - so, see my comment there. :)

2022-08-10 22:26 UTC, juliev0 commented
This was completed [here](https://github.com/argoproj/argo-workflows/pull/9334)

2022-08-10 22:26 UTC, closed without merging