Update argoserver.go
argoproj/argo-workflows pull request #9287
Opened 2022-08-04 12:15 UTC by sid8489

Add Header "X-Accel-Buffering: no" to argo server responses to improve buffering between argo server and client #9286

Fixes #TODO

2022-08-16 20:45 UTC, alexec requested changes

2022-08-16 20:45 UTC, alexec commented on server/apiserver/argoserver.go
> +		runtime.WithForwardResponseOption(func(ctx context.Context, w http.ResponseWriter, p proto.Message) error {
Can you please add a test to argo_server.go. You could use `TestInfo` maybe?

2022-10-01 00:52 UTC, closed without merging

2022-11-03 16:01 UTC, hummelm commented
I am experimenting the same issue regarding 
the text/event-stream (SSE) and the load balancer buffering.
I am going to test this patch with argo 3.4.2 to see if it fix it.

2023-03-14 11:41 UTC, DavidConnack commented
@alexec what would be needed to get this pr merged?