fix: default not respected in setting global configmap params. Fixes #9745
argoproj/argo-workflows pull request #9758
Opened 2022-10-06 19:25 UTC by rohankmr414

Signed-off-by: Rohan Kumar <rohan@pipekit.io>

Fixes #9745

2022-10-06 20:13 UTC, terrytangyuan requested changes
Could you add tests?

2022-10-07 15:21 UTC, alexec requested changes
Needs test.

2022-10-08 21:15 UTC, rohankmr414 commented
@terrytangyuan @alexec tests added

2022-10-10 16:17 UTC, terrytangyuan approved these changes

2022-10-10 16:35 UTC, merged